import re,sys,glob,os
D="/home/user/guardrail_research/benchtest/scratchpad/drafter/ma_pages/"
def norm(s): return re.sub(r"\s+"," ",s.replace("’","'").replace("“",'"').replace("”",'"')).strip().lower()
txt={os.path.basename(f):norm(open(f,encoding="utf-8",errors="replace").read()) for f in glob.glob(D+"*.txt")}
Q=[
("overview.txt","Model Armor is a Google Cloud service designed to enhance the security and safety of your AI applications"),
("overview.txt","Model Armor filters both input (prompts) and output (responses) to prevent the LLM from exposure to or generation of malicious or sensitive content."),
("overview.txt","Whether you are deploying AI in Google Cloud or other cloud providers"),
("overview.txt","Model Armor inspects each prompt and response independently as a single-turn request."),
("overview.txt","Model Armor doesn't decode or inspect encoded content, such as prompts encoded in Base64, hexadecimal, URL encoding, or ciphertext."),
("overview.txt","Model Armor doesn't support audio or video."),
("overview.txt","This filter is applied by default and cannot be turned off."),
("overview.txt","if the word count is fewer than three words, Model Armor returns NO_MATCH_FOUND"),
("overview.txt","scans only the first 256 URLs found in prompts and responses"),
("overview.txt","These filters can work in many other languages, but the quality of results might vary."),
("overview.txt","The Sensitive Data Protection filter supports English and other languages depending on the infoTypes that you selected."),
("overview.txt","Note: You can set confidence levels only for prompt injection and jailbreak detection and responsible AI safety filters."),
("overview.txt","Supported files are limited to 4 MB in size. If a file exceeds this limit, Model Armor skips scanning the file."),
("overview.txt","Model Armor doesn't screen images embedded within files."),
("overview.txt","Image screening is supported only in the us and eu multi-regions."),
("overview.txt","Model Armor doesn't screen images provided along with text in prompts and responses if you're using the SanitizeUserPrompt and SanitizeModelResponse methods."),
("overview.txt","Model Armor screens only a single image per request."),
("overview.txt","Visual scanning: Screens the visual content within images only using the advanced Sensitive Data Protection filter."),
("overview.txt","Model Armor operates as a stateless service, processing all prompts and model responses entirely in memory."),
("overview.txt","Set prompt injection and jailbreak detection filters to Medium."),
("overview.txt","Basic configuration only supports inspection operations"),
("overview.txt","Model Armor can accept existing inspection templates, which function as blueprints"),
("overview.txt","Decouple templates: Configure separate Model Armor templates for user prompts and model responses."),
("overview.txt","Model Armor can be purchased as a standalone service or as an integrated part of Security Command Center."),
("overview.txt","sensitive data protection (including topicality)"),
("overview.txt","Enforce custom topics:"),
("overview.txt","The calling service or integration point or Policy Enforcement Point (PEP) is responsible for blocking the further processing."),
("overview.txt","Model Armor doesn't support prompts that combine text and images in a single request."),
("manage-templates.txt","If you don't specify a confidence level, it is set to High by default."),
("manage-templates.txt","We recommend that you set the confidence level"),
("manage-templates.txt","The global endpoint (modelarmor.googleapis.com) doesn't support"),
("manage-templates.txt","INSPECT_ONLY: Model Armor inspects requests that violate the configured settings, but it doesn't block them."),
("reference_rest_v1_projects.locations.templates.txt","DETECTION_CONFIDENCE_LEVEL_UNSPECIFIED | Same as LOW_AND_ABOVE."),
("reference_rest_v1_projects.locations.templates.txt","fixed set of six info-types"),
("reference_rest_v1_projects.locations.templates.txt","LOW_AND_ABOVE | Highest chance of a false positive."),
("sanitize-prompts-responses.txt","PASSWORD: Clear text passwords in configs, code, and other text."),
("sanitize-prompts-responses.txt","The following additional Sensitive Data Protection infoTypes are scanned in the prompt for US-based regions"),
("sanitize-prompts-responses.txt","Don't include system prompts"),
("sanitize-prompts-responses.txt","StreamSanitizeUserPrompt: Streams and sanitizes user-provided text."),
("sanitize-prompts-responses.txt","Model Armor streaming methods don't support Sensitive Data Protection de-identification"),
("sanitize-prompts-responses.txt","Model Armor doesn't automatically detect the file type"),
("sanitize-prompts-responses.txt","Sensitive Data Protection de-identification is not supported for file-based prompts"),
("quotas.txt","1200 queries per minute (QPM) per project"),
("quotas.txt","Model Armor screens text up to 65,536 tokens (approximately 262,144 characters)"),
("quotas.txt","When you sanitize streaming text in real-time mode, Model Armor supports unlimited tokens."),
("quotas.txt","Maximum regular expression pattern length | 1,000 characters"),
("quotas.txt","Requests to ExternalProcessor | 600 QPM per project"),
("integrations.txt","only the Gemini Enterprise integration supports documents. All other integrations scan and sanitize only text."),
("integrations.txt","The Gemini Enterprise integration does not support data de-identification or masking."),
("model-armor-mcp-google-cloud-integration.txt","Model Armor sanitizes only the following MCP payloads"),
("model-armor-mcp-google-cloud-integration.txt","Don't enable the prompt injection and jailbreak filter unless your MCP traffic carries natural language data."),
("set-filter-version.txt","You can't specify different versions for individual filters."),
("set-filter-version.txt","The filter version setting doesn't affect the Sensitive Data Protection and malicious URL filters."),
("version-history.txt","v4 | 2026-09-18 | Minor updates have been made across prompt injection and jailbreak detection, and responsible AI filters to address reported false positives."),
("release-notes.txt","Model Armor is FedRAMP High compliant."),
("release-notes.txt","Streaming sanitization for text is generally available (GA)."),
("release-notes.txt","Model Armor supports data residency in-use compliance in Singapore (asia-southeast1). This region has limited feature support."),
("release-notes.txt","Template-specific exclusion rules are available in Preview."),
("release-notes.txt","Model Armor can sanitize data passed in as rich documents that have specific metadata labels."),
("release-notes.txt","Model Armor integration with Google and Google Cloud MCP servers is in General Availability."),
("release-notes.txt","The level of detail provided in the virusDetails field of the Antivirus filter scan results has been updated."),
("cloud.google.com_security_products_model-armor.txt","hybrid defense in-depth approach that combines rules-based controls, ML models, and powerful AI reasoning models"),
("cloud.google.com_security_products_model-armor.txt","Model Armor protects all LLMs (including Gemini, OpenAI, Anthropic, Llama, and more) via a REST API"),
("cloud.google.com_security_products_model-armor.txt","Detects malicious files, malware, and unsafe URLs within AI prompts and responses."),
("cloud.google.com_security-command-center_pricing.txt","When Sensitive Data Protection is enabled within Model Armor, there are no additional charges to use it."),
("reference_libraries.txt","pip install --upgrade google-cloud-modelarmor"),
("reference_libraries.txt","npm install @google-cloud/modelarmor"),
("reference_rest_v1_SanitizationResult.txt","PDF Scanning for only PDF is supported."),
("feature-availability-by-region.txt","Antivirus scanning"),
("model-armor-vertex-integration.txt","Sanitizing prompts and responses that contain documents or file uploads (such as PDFs) isn't supported in this integration."),
("model-armor-gemini-enterprise-integration.txt","Interactions with custom agents from your organization (such as ADK, A2A, and Dialogflow) are not screened."),
("model-armor-networking-integration.txt","The mechanism for this integration is through Service Extensions."),
("model-armor-langchain-integration.txt","ModelArmorSanitizePromptRunnable"),
("configure-exclusion-rules.txt","You can use exclusion rules for the following filters"),
("configure-floor-settings.txt","You cannot create or update a template that's less strict than the floor settings."),
]
bad=0
for f,q in Q:
    ok=norm(q) in txt.get(f,"")
    if not ok:
        bad+=1; print("MISS",f,"::",q[:110])
print(len(Q),"quotes;",bad,"missing")
