## Reviewer notes
Method: code read at the pinned clone (172c1074069eb88ec834124272c1b1c4f8893445, HEAD verified equal), not run. Live pages read with fetch_text.py (verbatim): dev.meta.ai Prompt Guard page, llama.com/llama-protections (redirects to dev.meta.ai, HTTP 200), HF gate pages for 86M and 22M (HTTP 200), HF API metadata for both repos, arXiv 2505.03574 html, PyPI simple index for llamafirewall and codeshield. WebFetch was not used. Quotes have straight quotation marks where the source uses curly ones.
1. Paper versus card (PL1 R5): the paper's table prints the 86M English AUC as ".98"; the card prints ".998". Both written as bullets; the other cells match.
2. Parameter counts (PL1 R4): HF safetensors totals 278,810,882 (86M) and 70,830,722 (22M) versus the card's "86M" and "22M" backbone parameters. The embedding-table explanation is [Inferred].
3. Language count (PL4 R2, PL6 R2): conflict C1 written as separate bullets (7: CodeShield README, protections page, paper section 4.4; 8: ICD README, LlamaFirewall README and docs, paper summary, code). The 16-member enum and 14-entry analyser map are reported as not documented as supported.
4. Latency (PL4 R5, PL6 R5): four statements (C2) kept as four bullets, none chosen.
5. Scanner name (PL2 R3): docs use PROMPT_INJECTION (adding-custom-use-case.md) but the enum has PROMPT_GUARD only (C3); two bullets.
6. Docs sample output (PL2 R5): how-to page prints reason 'prompt_guard' and benign reason 'default' with score 0.0; the single-scanner code path returns the scanner's own reason and score. New finding, not in the brief.
7. Code observations labelled [Inferred] and needing the bench to confirm (code read, not run): (a) PL2 builds a new scanner, and so reloads the model, on each scan call (llamafirewall.py:118); (b) PL6 Semgrep issues carry a raw severity string, so scan_code's BLOCK check (Severity.ERROR) may never fire for Semgrep findings (insecure_code_detector.py:282; codeshield.py:90); (c) temporary files are not removed on the fast-mode early returns (insecure_code_detector.py:129,137 before 151); (d) PHP Semgrep rules unreachable because the analyser map lists PHP as regex only; (e) Rust has no CODESHIELD rules of its own in config.yaml; (f) LlamaFirewall imports codeshield from the installed package first (code_shield_scanner.py:9-19), so PyPI codeshield 1.0.1 rather than the repo folder normally supplies the rules.
8. CWE counts (PL4 R2, PL6 R2): 47 (CODESHIELD rules, eight default languages), 63 (CyberSecEval rules, eight languages), 65 (all enum languages) are my counts of distinct CWE-nnn strings in cwe_id fields of regex YAML and generated Semgrep JSON (script in scratchpad/drafter/purplellama_cols_a/cwe_count.py). They are derived data; labelled [Inferred]. Rule counts (38 regex ids, 77 Semgrep ids in config.yaml; generated JSON rule counts) are plain counts of the files and labelled [Documented: repo].
9. Not read: Hugging Face card bodies (gated, HTTP 401), so card facts come from the repo MODEL_CARD.md files; equality with the HF body is [To be verified] (R8). The llama-cookbook inference.py and prompt_guard_tutorial were not read. PyPI sdists were not read. The per-language precision and recall figure in the paper is an image. The Code Shield notebook output cells were not examined.
10. Docs-site pages are cited through their pinned .md files only (five pages matched in P0). No live docs-site page was relied on for a quote in these four columns.
11. Header prefixes follow option B (per-tool). The checker may warn that several prefixes appear in one file; that is expected.
12. AUP (PL1 R8): the whole Llama 4 USE_POLICY.md was grepped for test, security, circumvent; only item 2.8 (line 37) is close. This is a licensing question for CP1/CP2, not a conclusion.
13. Cross-reference to Llama Guard (columns V to Z) appears in one Detail sentence each in PL1 R2 and R3 only, not in any Summary.
