# Cloak triage items. Each: k, f (files), c (class), p (priority), fl (flag), item, loc, src
# files: CK1 CK2 CK3 INV BR (files the item touches)
# flag: '' | 'CP1' | 'GAP' (honest gap)
# Placeholders {key} are replaced by T-ids by gen.py; {TERMS} and {LOGIN} are text macros.
TERMS = "Terms PDF (https://go.gov.sg/cloak-terms, 302 to file.go.gov.sg/cloak-terms.pdf, dated 24 July 2024, 15 pages)"
LOGIN = "API Guide and OpenAPI pages redirect to docs.developer.tech.gov.sg/auth/otp-login (HTTP 200 after redirect, not_logged_in, observed 2026-10-10)"
GROUPS = [
 ("Decisions, scope, headers and Covered-by mappings", [
  dict(k="q01", f="CK1 CK2 CK3 INV BR", c="b", p="H", fl="CP1",
   item="[CP1] Q01 column set: (a) CK1 to CK3, free text only (drafted default); (b) CK1 only, custom entities and reversible anonymisation folded in; (c) inventory only, no Table 3 columns. Evidence in CP1-1.",
   loc="BR Table 3 headers, Alternatives Q01, Open user questions Q01; CK1, CK2, CK3 all rows; INV Covered-by cells (CK1 named in 63 of 81, CK2 in 26, CK3 in 25; 73 non-marker cells change under (c), 32 under (b)); A RN-1, RN-2; B RN-1",
   src="User at CP1; closes when chosen. Under (b) the merger folds the mechanism-named CK2 and CK3 bullets into CK1 (A:13, 50, 62, 63, 102, 107 are already written that way); under (c) no column is merged"),
  dict(k="split", f="CK3 BR", c="b", p="H", fl="CP1",
   item="[CP1] Should CK3 split by direction (anonymise side versus restore side) under R002, or stay one column? Evidence in CP1-2; recommended default: one column.",
   loc="CK3 R1 (B:178-186), R3 (B:203-214), R5 (B:240-248), R6 (B:254-262); R2, R4, R7 unsplit; B RN-2; BR Scope Direction (R002)",
   src="User at CP1 (R002 was decided by the user, definition clarified by main); no source can answer because the API schema is login-gated ({dir})"),
  dict(k="hdr", f="BR CK2 CK3 INV", c="a", p="M", fl="",
   item="Header text drift: the brief still lists the old CK2 and CK3 headers (\"(regex and LLM)\", \"(secrets and salts)\") in four places, while the drafts and INV use main's tweaks (\"(lists, regex and LLM)\", \"(encrypt and restore)\"). Prefix `Cloak:` was ruled by main (R009, R031 precedent); fixed at CP1, frozen after CP2.",
   loc="BR lines 24-25, 34, 180, 183; B:5, B:174; INV Covered-by cells; A RN-1; B RN-1; INV-RN 1",
   src="Main's queue rows (cloak P1 Q4 header tweaks; q03 prefix). Merger records the change in cloak_changes.md; mechanical check: the three tweaked headers pass check_drafts (columns 0/0, inventory 0/0 with those headers). Not put to the user"),
  dict(k="cov", f="INV CK1 CK2 CK3", c="a", p="M", fl="",
   item="Covered-by mappings to reconcile: (i) Decrypt row `CK1; CK3` becomes `CK3` only (main); (ii) Pseudonymise row `CK1; CK3` although the CK3 header no longer names salts (CK3 R4 and R6 still carry the salt bullets); (iii) Templates row CK1 only, yet CK2 R6 says a custom entity configuration is saved as a template; (iv) block (f) Presidio row CK1 only, yet its Encrypt-page evidence supports CK3; (v) pasted-text and file-limit rows CK1 only, yet CK2 R3 and R6 and CK3 R6 repeat them",
   loc="INV(d) lines 81-83; INV(a) Templates (line 16); INV(f) Presidio (line 124); INV(e) lines 91-94; CK2 R6 B:103; CK3 R6 B:263; BR block (d) mapping; INV-RN 1",
   src="Inventory against column Detail; no source needed. Brief block (d) says Encrypt, Pseudonymise and Decrypt are `CK1; CK3`, which main overrode for Decrypt only. Merger decides (ii) to (v); the check_drafts header test is satisfied either way"),
  dict(k="incl", f="CK1 CK2 INV BR", c="a", p="M", fl="",
   item="Inclusion-list placement: the brief's CK1 coverage text includes per-entity Inclusion lists, the brief block (c) and INV(c) put the Inclusion row under CK2 only, CK1 R6 carries the Inclusion bullet (limit \"500 entries\"), and CK2 R1 and R6 carry it too. Suggested reconciliation: Covered-by `CK1; CK2` for the Inclusion row, one limit bullet in CK1 R6, the fuller pair of limit quotes in CK2 R6.",
   loc="BR What each column covers (CK1) versus block (c); INV(c) Inclusion row (line 63); CK1 R6 A:95, A:97; CK2 R1 B:14, R6 B:96; A RN-1; queue cloak P2 note",
   src="Main: triage checks against the inventory mapping, merger reconciles. Inventory mapping and CK1 text disagree; no source needed"),
  dict(k="cnt", f="INV BR", c="a", p="M", fl="",
   item="Inventory row counts and build config: finals are 10, 7, 26, 9, 25, 4 = 81 rows (brief targets 10, 7, 25, 9, 16, 3); adding the planned Sentinel row ({sentrow}) makes block (b) 8 and the total 82. The config module needs BLOCKS counts, the `covered` header and a markers tuple with legacy, inventory-only and planned markers.",
   loc="INV-RN 2, INV-RN 5, Self-check; BR Inventory section; queue cloak P2 inventory Q1 to Q4",
   src="gr-xlsx-writer at P8; check_drafts MARKERS already allows the three markers (R011). Counts re-run in this triage: tables 10, 7, 26, 9, 25, 4"),
  dict(k="sentrow", f="INV BR", c="a", p="M", fl="",
   item="Add the planned \"Sentinel integration\" row to INV(b) with marker `— (planned, not in Table 3)` and a cross-reference to GovTech Sentinel: PII detection and masking (AWS Bedrock) (SN6, column AF). Facts: playbook \"Direct integration with the Sentinel API is coming soon.\" and the code stub, both `[Documented: repo govtech-responsibleai/playbook@45908b48]`; Sentinel docs checked for \"cloak\", no hit `[Not disclosed]`. Status and date: see {sentint}.",
   loc="INV(b) new row after line 34; CK1 R4 A:69-70, R8 A:141; INV-RN 5 (\"not used\"); queue cloak P2 inventory Q1 to Q4",
   src="Main's instruction. Playbook page at the pin (raw read, same text at HEAD 97338569); aiguardian.gov.sg /docs and /docs/wiki/Sentinel-Guardrails absence. The (b) columns (Path, Audience, Security level, Ceiling, Applies to, Caveats) need a fit; the planned marker must be in the config"),
  dict(k="c3", f="CK1 CK2 INV BR", c="a", p="M", fl="",
   item="C3 access wording: the playbook calls Cloak \"GovTech's dedicated internal service\"; the Cloak Guide and portal say it is open to select non-government entities. Only CK2 R8 carries it; CK1 and INV do not. Give both as two labelled facts in the INV(b) non-WOG row and the CK1 R6 access bullet, or keep it in R8.",
   loc="CK2 R8 B:138; CK1 R6 A:108; INV(b) line 29; BR C3; A RN-3; B RN-5",
   src="Playbook page at pin 45908b48 (quote); FAQ and registration guide (quotes); README rule 4 (two bullets, each labelled)"),
 ]),
 ("Licensing and terms (class c)", [
  dict(k="t347", f="CK1 CK2 CK3 INV BR", c="c", p="H", fl="",
   item="Terms clause 3.4.7: the user shall not \"perform any benchmarking tests or analyses of the Service\". Whether a comparison bench by an approved user is within it; the Terms define no benchmarking term (INV says it checked all 15 pages).",
   loc="CK1 R7 Summary (A:114), A:118, R8 A:129; CK2 R7 B:116, R8 Summary B:124, B:126; CK3 R7 B:272, R8 B:282; INV(e) line 108; BR Scope, Licensing item",
   src="{TERMS}. P5 resolver re-reads clause 3.4 and any definitions clause and quotes; no interpretation. Main (queue): clause recorded as documented, permitted use stays an open R8 question decided before bench testing (R025 ruling 1 pattern; R032 wording)"),
  dict(k="t33", f="CK1 CK2 CK3 INV", c="c", p="H", fl="",
   item="Terms clause 3.3: non-public-sector use is restricted to a Purpose GovTech consented to in writing (including email), and a changed Purpose needs prior written consent. The R7 Summaries rest on \"approved access\"; whether a bench could obtain consent.",
   loc="CK1 R7 A:117; CK2 R7 B:115, R8 B:127; CK3 R7 B:271, R8 B:284; INV(b) line 29, INV(e) line 107; FAQ (\"agreed with the Cloak team on the purpose of use\")",
   src="{TERMS} clause 3.3 and the definition of Public Sector Entities (not quoted in any draft); FAQ page. Per R032 the drafts only suggest; agents do not approach GovTech (R019 read-only)"),
  dict(k="t349", f="CK1 CK3 INV", c="c", p="M", fl="",
   item="Terms clauses 3.4.9 and 3.4.11 (no sharing of \"license keys\", no third-party access) against the Secrets Manager's sharing of secrets between users and against any bench run by someone other than the approved user.",
   loc="CK1 R7 A:120; CK3 R6 B:261-262, R7 Summary B:268, B:272, R8 B:283; INV(e) line 109",
   src="{TERMS} clause 3.4; whether secret sharing is sharing of licence keys is not interpreted. Resolver quotes the clauses and any defined terms"),
  dict(k="sch22", f="CK1 CK3 INV BR", c="c", p="M", fl="",
   item="Schedule 2.2 (\"not permitted to use this Service if you are not using the Service for and on behalf of your Agency\"; the Terms bind the user individually) and the FAQ statement that users are \"legally bound by Cloak's Terms of Use\" with \"no separate agreement\", which is in the brief but in no draft.",
   loc="CK1 R7 A:119; CK3 R8 B:284; INV(e) line 111; BR Licensing item",
   src="{TERMS} Schedule 2; FAQ page (faqs.md). Resolver adds the FAQ quote to INV(e) if wanted"),
  dict(k="sch46", f="CK1 CK2 CK3 INV", c="c", p="M", fl="",
   item="Schedule 4.6 data ceiling \"Confidential (Cloud-Eligible) \\ Sensitive (High)\" (separator as extracted by pypdf) beside the FAQ's \"up to Confidential Cloud-Eligible (CCE), Sensitive-High (SH)\". Sensitive test data is decided at bench design (R019).",
   loc="CK1 R6 A:109; CK2 R6 B:108; CK3 R6 B:264; INV(b) lines 28-29, INV(e) line 103",
   src="{TERMS} Schedule 4.6; check how the PDF renders the separator; FAQ page. The meaning of \"above\" is not interpreted"),
  dict(k="priv", f="INV BR", c="c", p="M", fl="",
   item="Privacy Statement (dated 1 December 2022, Privacy Annex \"Dataset uploaded by user ...\") is older than the Terms (24 July 2024) and the 2026 docs; no draft checks it against the FAQ retention (\"purged within 24 hours\") or states API-call retention.",
   loc="INV(e) lines 102, 114; A RN-9 (\"not used\"); BR Official sources",
   src="Privacy PDF (go.gov.sg/cloak-privacy, 302 to file.go.gov.sg/cloak-privacy.pdf, 4 pages); resolver quotes retention and purpose wording and states whether it matches the FAQ"),
  dict(k="t42", f="CK1 INV", c="c", p="M", fl="",
   item="Terms clauses 4.2 (routine deletion) and 6.1 (data licence) are named in A RN-9 as service-wide facts for the inventory but appear in no row of INV(e) and in no column.",
   loc="A RN-9; INV(e) (absent)",
   src="{TERMS}; resolver reads both clauses and proposes rows; no interpretation"),
  dict(k="t91", f="CK1 INV", c="c", p="L", fl="",
   item="Terms clause 9.1 (\"as is\" and \"as available\") and 9.1.1 (warranty disclaimer for accuracy, completeness, correctness) beside the vendor's \">97% recall\" claim; no draft puts them side by side.",
   loc="INV(e) line 112; CK1 R5 A:82",
   src="{TERMS} clause 9; present both without comment"),
  dict(k="t346", f="INV BR", c="c", p="L", fl="",
   item="Terms clauses 3.4.6 (managed service provider or timesharing), 3.4.10 (code of a third party) and 3.7 (no unreasonable or disproportionately large load): relevance to a bench is not stated.",
   loc="INV(e) line 110; BR scope",
   src="{TERMS}; quotes already verbatim; R032 keeps any bench implication a suggestion"),
  dict(k="t15num", f="INV BR", c="c", p="L", fl="",
   item="Terms numbering: the row says clause 15, the quoted cross-reference says \"clause 14.2 above\", and INV notes clauses 14.2 and 14.3 against 15.2 and 15.3 in the PDF; the brief says clause numbers are to be read at the PDF.",
   loc="INV(e) line 113; BR (e) row list",
   src="{TERMS} raw page text; keep numbers as printed and say so in the cell"),
  dict(k="tver", f="INV BR", c="c", p="L", fl="",
   item="Terms version and link currency: the PDF is dated 24 July 2024 while docs and portal are dated 2026; the FAQ links https://www.cloak.gov.sg/terms (HTTP 404) and the live copy is reached through go.gov.sg/cloak-terms; whether a later version exists is not stated.",
   loc="INV(b) line 29, INV(e) lines 106, 114; BR C9; INV-RN 4",
   src="HTTP facts already recorded (observed 2026-10-10); the later-version question is [Not disclosed] (checked the FAQ and the PDF). Resolver re-reads the go.gov.sg redirect"),
  dict(k="licc", f="INV BR", c="c", p="L", fl="",
   item="Component licences in INV(f): spaCy MIT, en_core_web_sm 3.8.0 MIT with an OntoNotes 5 source \"commercial (licensed by Explosion)\", Presidio MIT, PyCryptodome BSD 2-Clause plus public domain, PyCrypto \"Public Domain\" on PyPI with no owner named. The drafts say none is evidence for what Cloak runs. The PyPI page is the Credits link, not an owner's page, yet carries a plain [Documented].",
   loc="INV(f) lines 123-126; BR block (f)",
   src="Owners' licence files at the pins (R019 allows); PyPI label to confirm (hygiene)"),
 ]),
 ("API, direction and login-gated gaps (honest gaps)", [
  dict(k="dir", f="CK1 CK2 CK3 INV BR", c="b", p="H", fl="GAP",
   item="R002 direction: no public page shows an input or output flag; whether the API has one is not known. All three R3 Summaries say no direction flag or setting was found and treat prompts, responses and retrieved text alike.",
   loc="CK1 R3 Summary A:37, A:44, R8 A:130; CK2 R3 Summary B:37, B:45; CK3 R3 Summary B:201, B:211; INV(b) line 33; BR Scope Direction",
   src="{LOGIN}. Only an approved account could answer; stays open for the bench (R019). Checked per bullet: all 80 Cloak Guide pages, 7 portal pages, home page, Web UI text"),
  dict(k="apisch", f="CK1 CK2 CK3 INV", c="b", p="M", fl="GAP",
   item="API request and response schemas, auth header, rate limits, latency or SLA, text limit on the API, retention of API calls, effect of the Wednesday maintenance banner on the API, and whether a system or user prompt is accepted as context.",
   loc="CK1 R3 A:47, R5 A:86, R6 A:105-106, R8 A:130; CK2 R3 B:50, R5 B:91, R6 B:106; CK3 R5 B:250, R6 B:260; INV(b) lines 30-33, INV(e) lines 91, 102, 105",
   src="Login-gated ({LOGIN}); checked pages named in each bullet. Closed government service: say not public, never speculate (R007 item 6)"),
  dict(k="apipar", f="CK1 CK2 INV", c="b", p="M", fl="",
   item="API versus Web UI: the API guide says it \"gives you the same anonymisation capabilities as the Web UI\" and also lists parameters not in the Web UI (context words, per-pattern scores, allow list). Whether results are identical, and which features are API only.",
   loc="CK1 R6 A:106-107, R8 A:136; CK2 R6 B:105, R8 B:137; INV(b) lines 30-31",
   src="API docs gated; needs testing on both routes with approved access"),
  dict(k="llmapi", f="CK2", c="b", p="M", fl="GAP",
   item="Whether the LLM-enabled custom entity is available on the API or the real-time path; the public API guide names regex patterns and context words only, and LLM jobs may take up to 8 hours.",
   loc="CK2 R3 B:46, R8 B:131",
   src="API Guide gated; checked the public API guide page, FAQs and portal pages (named in the bullet)"),
  dict(k="recon", f="CK3 INV", c="b", p="M", fl="GAP",
   item="\"Reconstruct endpoint for FTA API\" (release note v2.0.1, 4 December 2023): what it does; and the `/analyze` endpoint with a caller-maintained mapping table named on the Replace (Unique) page.",
   loc="CK3 R1 B:184-185, R3 B:210, R8 B:286; INV(b) line 33; A RN-10",
   src="One release-note line and one docs sentence; the API pages are gated. Honest gap"),
  dict(k="helper", f="CK3 INV", c="b", p="M", fl="GAP",
   item="Free-text decryption helper script and bulk restore API (\"looping through rows in a CSV\"): parameters not public; the Web UI decrypts one value at a time.",
   loc="CK3 R1 B:181, R6 B:260; INV(a) line 13, INV(b) lines 32-33, INV(d) line 83",
   src="Linked helper page gated (login redirect observed 2026-10-10)"),
  dict(k="lat", f="CK1 CK2 CK3 INV", c="b", p="M", fl="",
   item="Latency of one short prompt and the \"real-time\" wording: only the CSV time table and \"fast processing time\" for text are given; real-time use through the Web UI is not stated (jobs are download requests).",
   loc="CK1 R3 A:43, R8 A:134; CK2 R8 B:134; CK3 R8 B:294; INV(b) line 28, INV(e) line 97",
   src="Needs measurement on an approved API route (R019: nothing run in research)"),
 ]),
 ("Mechanism, model identity, versions and hosting", [
  dict(k="ner", f="CK1 INV", c="b", p="H", fl="GAP",
   item="Which model backs the baseline entities (spaCy is given only as an example), its version and tuning, and which entity uses the model versus rules. The R4 Summary says \"model not named\".",
   loc="CK1 R4 Summary A:52, A:54-56, R8 A:131; INV(c) intro (line 38), 10 \"Method not named\" rows; INV(f) spaCy row (line 123)",
   src="Checked entity pages, FAQ, Credits, release notes, portal pages and the 2023 deck: not stated. Closed service, no repo; no public document expected to answer (R007 item 6)"),
  dict(k="entgap", f="CK2 INV", c="b", p="L", fl="GAP",
   item="Per-entity detail gaps on entity pages: method not named for 10 entities, credit-card checksum, non-Singapore passports, Exceptions matching rules, postal-code \"improving our algorithm\", custom regex dialect, flags and timeouts.",
   loc="INV(c) lines 42, 44, 46, 51, 52, 54, 57-59, 61-62, 65; CK2 R4 B:59, R8 B:135",
   src="Entity pages checked per cell; the custom-regex page points only to regex101.com and pair.gov.sg"),
  dict(k="pres", f="CK1 CK2 CK3 INV", c="b", p="M", fl="GAP",
   item="\"Built on Presidio\" stays [Inferred] (shared tag names, the Encrypt page's text about Presidio's encryption, the entity-types link; Credits lists neither Presidio nor spaCy). CK3 R4 adds a token-layout difference that points the other way.",
   loc="CK1 R4 A:66-68, R8 A:131; CK2 R4 B:73; CK3 R4 B:221, B:232-233, R8 B:291; INV(c) intro, INV(f) line 124",
   src="No GovTech page says it; testing could compare outputs but not prove provenance. Label rule from the brief: Inferred"),
  dict(k="llmmodel", f="CK2 INV", c="b", p="M", fl="GAP",
   item="Language model behind the LLM-enabled entity (name, size, version, prompt template) and whether the Beta label is still current.",
   loc="CK2 R4 B:66, R8 B:128; INV(a) line 12",
   src="Checked intro, add-entities, write-prompts, three samples, FAQs, home, portal, release notes, Credits, 2023 deck, playbook: not stated"),
  dict(k="deployed", f="CK1 CK2 CK3", c="b", p="M", fl="GAP",
   item="Deployed version and ship dates of features documented in 2026 but absent from the release notes (Replace (Unique), PERSON Alias, SG_ADDRESS recognisers, LLM entities).",
   loc="CK1 R4 A:65, R8 A:135; CK2 R4 B:67; CK3 R4 B:234",
   src="Release notes stop at v2.2.2 (checked in full); not stated elsewhere"),
  dict(k="newest", f="CK1 CK2 CK3 BR", c="a", p="M", fl="",
   item="\"Newest release note\" wording: v2.2.2 (4 August 2024) is listed above v2.2.1 (28 August 2024), and v2.2.0 and v2.1.9 share 07 August 2024; the drafts say v2.2.2 is the newest. CK3 R4 B:234 also labels a positive fact [Not disclosed].",
   loc="CK1 R4 A:64; CK2 R4 B:67; CK3 R4 B:234; BR C6; A RN-3",
   src="release-notes.md at source. Suggested: \"highest version v2.2.2 (4 August 2024); latest dated entry v2.2.1 (28 August 2024)\"; split fact from absence"),
  dict(k="gcc1", f="CK1", c="a", p="H", fl="",
   item="CK1 R4 Summary says \"hosted on GovTech's cloud\"; the Detail says Government Commercial Cloud (GCC) and \"AWS GCC 2.0\" and never calls it GovTech's. Not entailed.",
   loc="CK1 R4 Summary A:52; A:59",
   src="Drafting fix, no research: \"hosted on the Government Commercial Cloud\" (Summary 33 words, room)"),
  dict(k="gcc3", f="CK3", c="a", p="M", fl="",
   item="CK3 R4 Summary says \"Hosting is Government Commercial Cloud\", but CK3 Detail has only \"AWS GCC 2.0\" (B:231); the expansion of GCC sits in CK1 R4 and CK2 R4.",
   loc="CK3 R4 Summary B:216, B:231",
   src="Add a bullet quoting the FAQ line (\"Cloak's Government Commercial Cloud (GCC) environment\") or reword the Summary"),
  dict(k="v201", f="CK1 CK3 BR", c="a", p="L", fl="",
   item="Release-note cross-check: CK1 R4 says v2.0.1 \"added Word support\"; the brief and CK3 R3 give v2.0.1 as \"[API] Reconstruct endpoint for FTA API\". Both may be true; the CK1 bullet also holds three release facts under one label.",
   loc="CK1 R4 A:64; CK3 R3 B:210; BR Release notes",
   src="release-notes.md, entries v2.0.1 and v2.1.0"),
 ]),
 ("Published numbers and documented behaviour", [
  dict(k="recall", f="CK1 CK2 INV", c="b", p="H", fl="GAP",
   item="\">97% recall for key PIIs like Name, NRIC and Email\": method, data set, precision, per-entity and per-language figures are not published; the R5 Summary states the claim and its limits.",
   loc="CK1 R5 Summary A:72, A:82-83, R8 A:132; CK2 R5 B:89-90, R8 B:129; INV(c) intro (line 38)",
   src="Checked home, overview, FAQs, features page and the 2023 deck: one claim, no method. Public document not expected; a bench measurement would be the only answer. Terms 9.1.1 ({t91}) sits beside it"),
  dict(k="acc", f="CK2 CK3", c="b", p="M", fl="",
   item="Accuracy of list, regex and LLM custom entities, and round-trip accuracy or failure rate of encrypt and restore: none published.",
   loc="CK2 R5 B:90, R8 B:129; CK3 R5 B:249",
   src="Needs testing; checked home, overview, FAQs, custom pages, samples and the 2023 deck"),
  dict(k="count", f="CK1 INV BR", c="a", p="H", fl="",
   item="Entity count: the R2 Summary says \"Seventeen entity groups\" (a tally of the entity-types page); the vendor says \"20+\" (FTA intro, Features) and \"17+\" (portal FAQs); the drafter's own tally is 20 tags [Inferred]. Main ruled: R2 keeps the documented 17 groups, the two vendor counts stay as two bullets.",
   loc="CK1 R2 Summary A:16, A:18-22; INV(c) intro; BR C1; A RN-3, RN-5",
   src="entity-types/intro.md and the address page: recount groups and tags at source (class a); what the deployed UI exposes is a UI check. README rule 4 for the two vendor statements"),
  dict(k="conf30", f="CK1 CK2 INV", c="b", p="H", fl="",
   item="Confidence default 0.30 and the 0 to 1 range rest on image captions, not body text; the R5 Summary states the default.",
   loc="CK1 R5 Summary A:72, A:80; CK2 R5 B:83; INV(e) line 100; A RN-4; B RN-8",
   src="Caption read in the raw .md; confirm in the Web UI. Keep [Documented] with the source type noted (brief)"),
  dict(k="confscope", f="CK1 CK2 INV", c="b", p="M", fl="",
   item="Confidence scope: the portal says \"Adjust detection sensitivity per entity type\", the guide shows one slider; CK1 R5 puts both sides in one [Documented] bullet while INV(e) labels the same question [Not disclosed]; whether the threshold applies to list, regex and LLM entities.",
   loc="CK1 R5 A:81, R8 A:137; CK2 R5 B:84, R8 B:132; INV(e) line 100",
   src="Hygiene: two bullets, one label each (README rule 4), align the two files; behaviour needs testing"),
  dict(k="w500", f="CK1 CK2 INV", c="b", p="H", fl="",
   item="Fixed-list and Inclusion limit: \"500 words\" (fixed-list page; Inclusion page \"first 500 words\") against \"up to 500 entries\" (Inclusion page). The CK2 R6 Summary says \"up to 500 words\"; CK1 R6 mixes both units in one bullet.",
   loc="CK2 R6 Summary B:93, B:95-96, R8 B:136; CK1 R6 A:97; INV(c) lines 63-64, INV(e) line 99; B RN-6b",
   src="Main (queue): limit wording stays R8, needs testing (501 items against 501 words). The Summary names one unit; merger may write \"up to 500 entries or words\" or similar"),
  dict(k="llmlim", f="CK2 INV", c="b", p="M", fl="",
   item="LLM entity limit per dataset (\"1 per dataset, up to 5,000 documents\") against \"normally one per project\" (FAQ). Both are quoted in CK2 R4, but CK2 R8 has no bullet for it; INV(e) gives only \"per dataset\" while INV(c) gives both.",
   loc="CK2 R4 B:63, B:65; B RN-6a; INV(c) line 66, INV(e) line 98",
   src="Main: limit wording stays R8 (needs testing). Drafting: add the R8 bullet and the FAQ quote to INV(e)"),
  dict(k="doc5000", f="CK2", c="b", p="L", fl="",
   item="Unit of \"up to 5,000 documents\" and processing time per document (documented times are for datasets).",
   loc="CK2 R8 B:134",
   src="Needs testing"),
  dict(k="lang", f="CK1 CK2 INV", c="b", p="M", fl="GAP",
   item="Language coverage beyond roman-script names (Chinese-character, Tamil, Malay text) for the baseline detector, regex and the LLM entity.",
   loc="CK1 R2 A:27, R8 A:133; CK2 R2 B:34, R8 B:130; INV(c) PERSON row (line 42)",
   src="Checked entity pages, FAQs, home, portal, custom pages: not stated; needs testing"),
  dict(k="dob", f="CK1 INV BR", c="b", p="M", fl="",
   item="Dates of birth and vehicle plate numbers: named on the portal Features and FAQs pages, with no entity page in the Cloak Guide; whether DATE_TIME catches a date of birth (the only [To be verified] in the columns).",
   loc="CK1 R2 A:29-31 (TBV A:31), R8 A:139; INV(c) line 67 (TBV), DATE_TIME line 59; BR C2; A RN-3",
   src="Two official sources differ in coverage; keep both bullets (README rule 4); needs a UI test"),
  dict(k="chk", f="CK1 INV", c="b", p="M", fl="",
   item="Where checksum validation (NRIC, UEN), global phone detection and Enhanced Detection for names are switched on: named in the FAQ, no page shows the control; the entity pages say validation and global coverage are disabled.",
   loc="CK1 R6 A:104, R8 A:138; INV(c) NRIC, PHONE_NUMBER, SG_UEN rows (lines 43, 45, 60)",
   src="Drafters checked NRIC, usage guide and confidence pages; needs a UI check"),
 ]),
 ("Techniques, reversibility and key handling", [
  dict(k="maskhyg", f="CK1 INV", c="a", p="M", fl="",
   item="Mask page conflict inside one page: \"Suffix: masks the starting characters\" and \"Prefix: masks the ending characters\" against an example that keeps the first three digits and is labelled \"suffix masked value\". INV(d) holds both under one [Documented] label (README rule 4 needs two bullets); CK1 R6 states the default type Suffix without the conflict, in a bullet that also holds Alias.",
   loc="INV(d) Mask row (line 78); CK1 R6 A:98",
   src="masking/intro.md raw read; two labelled facts in INV; add the conflict note to CK1 R6 or drop the Suffix default there"),
  dict(k="maskbeh", f="CK1 INV", c="b", p="L", fl="",
   item="Which end is masked by default (3 characters, type Suffix, character \"-\").",
   loc="INV(d) line 78; CK1 R6 A:98",
   src="Needs a Web UI test"),
  dict(k="revlab", f="CK3 INV", c="a", p="M", fl="",
   item="Reversibility labelled two ways: INV(d) says \"No [Inferred]\" for Replace, Redact and Mask but [Not disclosed] for Replace (Unique), NRIC masking and Alias; CK3 R2 and R8 give [Not disclosed] for the same question across Replace, Redact, Mask and Alias.",
   loc="INV(d) lines 75-80; CK3 R2 B:196, R8 B:290",
   src="R020 (absence is [Not disclosed]) against R015 (a conclusion from a feature description is [Inferred]); pick one convention and align both files"),
  dict(k="ru", f="CK1 INV", c="b", p="L", fl="GAP",
   item="Replace (Unique) on pasted text; mapping-table restore for Replace (Unique); Alias algorithm and consistency; NRIC masking mechanics; Exceptions matching rules.",
   loc="CK1 R6 A:101, R8 A:140; INV(d) lines 76, 79, 80; INV(e) line 101; INV(c) Exceptions row (line 62)",
   src="Pages list neither available nor unavailable or give no mechanics; needs testing"),
  dict(k="salt", f="CK3 INV BR", c="b", p="M", fl="",
   item="C4 salts: the Pseudonymisation page says \"Custom salt values will be included in the future\" while release notes list \"salt parameter\" (v2.1.0) and \"custom salts and user managed salts\" (v2.1.4). INV writes \"probably stale [Inferred]\"; CK3 gives no conclusion.",
   loc="CK3 R4 B:228-229, R8 B:292; INV(d) line 81; BR C4",
   src="Both quoted already; which is current needs the Web UI; align the INV wording with CK3"),
  dict(k="enc", f="CK3 INV", c="b", p="M", fl="GAP",
   item="Encrypt details: key length and format, whether Cloak generates keys, IV storage, token layout (a 16-byte decode of the page example) and whether one value always gives one ciphertext; the last two are [Inferred].",
   loc="CK3 R4 B:221, R5 B:246, R6 B:257, R8 B:288; INV(d) line 82; B RN-7",
   src="Derived from a base64 decode of one example; the Secrets Manager page has captions only; needs a round-trip test"),
  dict(k="fail", f="CK3", c="b", p="M", fl="",
   item="Free-text failure behaviour: wrong secret, damaged token, secret not shared with the user; tabular decryption writes failed_cells.csv as a contrast.",
   loc="CK3 R5 B:247-248, R8 B:289",
   src="Pages show no error handling; needs testing"),
  dict(k="multi", f="CK3 INV", c="b", p="M", fl="",
   item="Whole-reply restore: the Web UI decrypts one value at a time; whether one call can restore a text with several tokens, and whether a model keeps a base64 token intact ([Inferred]).",
   loc="CK3 R3 B:208, B:213, R8 B:285, B:293; INV(a) line 13",
   src="Needs testing with approved access; the Summary relies on the documented one-value-at-a-time statement"),
  dict(k="deck", f="CK1 CK3", c="b", p="M", fl="GAP",
   item="Currency of the 2023 deck: mapping table, \"Transformer Module\", \">20 LLM products\" (11 September 2023, \"may have changed\"). The CK3 R5 Summary uses the deck's mapping-table return.",
   loc="CK1 R3 A:49-50, R5 A:87; CK3 R1 B:186, R3 B:209, R5 Summary B:238, B:245, R8 B:287",
   src="Deck dated; later docs are silent on a mapping table; no public update expected"),
  dict(k="slide", f="CK1 CK3", c="a", p="M", fl="",
   item="Slide 22 wording came from the pypdf text layer, and A RN-8 says the layout order of labels is not guaranteed; CK1 R3 and CK3 R3 read the flow direction (anonymise before the model, \"Anonymised Response\" back through the Transformer Module) from it.",
   loc="CK1 R3 A:49-50; CK3 R3 B:209; A RN-8",
   src="Re-read the slide with a layout-preserving extraction at https://www.usenix.org/system/files/pepr23_slides-tang.pdf (page 22); quote only what the layout supports"),
  dict(k="custom", f="CK2", c="b", p="M", fl="",
   item="Custom-entity behaviour: which entity wins when a custom and a built-in entity match the same span; whether custom matches appear in the Findings table with a score; whether the 0.30 threshold applies to them.",
   loc="CK2 R5 B:82, B:84, R8 B:132-133",
   src="The structured page only advises disabling or tuning the built-in entity; needs testing"),
 ]),
 ("Summary entailment and labels", [
  dict(k="learns", f="CK2", c="a", p="H", fl="",
   item="CK2 R4 Summary says the Beta LLM entity \"learns from 3 to 5 examples\"; the page says few-shot prompting \"without fine-tuning\".",
   loc="CK2 R4 Summary B:52; B:13, B:99",
   src="Drafting fix: \"is prompted with 3 to 5 examples\" (Summary 34 words, room)"),
  dict(k="findings", f="CK2", c="a", p="H", fl="",
   item="CK2 R5 Summary says each custom match is transformed and \"the Findings table lists type, transformation, original, anonymised text and score\", while Detail B:82 says whether custom entities appear there with a score is [Not disclosed].",
   loc="CK2 R5 Summary B:75; B:81-82",
   src="Drafting fix: reword the Summary to the documented transformed output and drop the implied custom-entity rows in the table"),
  dict(k="headroom", f="CK1 CK2 CK3", c="a", p="L", fl="",
   item="Summaries near the cap (words excluding the label; limit 45, R7 60): CK1 R3 44, CK3 R3 44, CK1 R5 43, CK1 R1 42, CK2 R3 42, CK2 R6 42, CK3 R1 42. The build counts the label (lesson 18); all still pass, but the rewrites for {gcc1}, {learns}, {findings} and {w500} have 1 to 3 words of room in places.",
   loc="Style issues item 1",
   src="check_drafts (0/0) and lesson 18"),
 ]),
 ("Cross-source and status items", [
  dict(k="sentint", f="CK1 CK2 INV", c="b", p="M", fl="GAP",
   item="Sentinel integration status and date: the playbook says \"coming soon\" and the code stub says it is on the roadmap; no date; Sentinel docs pages checked, no mention.",
   loc="CK1 R4 A:69-70, R8 A:141; CK2 R8 B:138; INV(b) new row ({sentrow})",
   src="Playbook only; closed government service, say not public (R007 item 6)"),
  dict(k="ctx", f="CK1 CK2", c="b", p="L", fl="GAP",
   item="\"ContextGuard Demo\" on the Video Guides page: relation to Cloak not stated (title and section labels only).",
   loc="CK1 R8 A:142; CK2 R8 B:139; BR gaps",
   src="Checked the Cloak Guide, portal pages and home page; no row added (brief)"),
  dict(k="mdg", f="INV BR", c="b", p="L", fl="GAP",
   item="MDG (C5): the portal lists Mock Data Generation as a Cloak feature; the Mirage site says Mirage offers it and that it \"is available via API through Cloak\"; the Cloak Guide has no MDG page; the Web UI route is not stated. INV says \"not reconciled here\" though the Mirage quote already links it to the Cloak API.",
   loc="INV(a) lines 17, 19; BR C5; INV-RN 4",
   src="Main: inventory only, both claims recorded, no contact. Drafting: quote, do not decide; soften \"not reconciled\""),
  dict(k="pov", f="INV", c="b", p="L", fl="GAP",
   item="Status basis: FTA and Tabular are \"Available [Inferred]\" from the feature list, while the portal overview carries a PROOF OF VALUE badge whose meaning no page states.",
   loc="INV(a) lines 11, 14",
   src="No page defines the badge; checked the overview and home page"),
  dict(k="defon", f="INV", c="a", p="L", fl="",
   item="16 baseline rows carry \"On [Inferred] (premise P-ON)\"; the premise is a verbatim usage-guide sentence (\"By default, Cloak scans your text for all available Entity Types ...\"). A resolver may upgrade to [Documented] only with that quote and URL recorded; SG_ADDRESS_STREET stays Off.",
   loc="INV(c) lines 42-61",
   src="usage-guide.md; README rule 1 (resolution quote)"),
  dict(k="c7", f="INV BR", c="a", p="L", fl="",
   item="C7 file-limit history: v2.0.3 \"Maximum 10 columns\" and 100k rows against the current 500 MB per file and the FAQ's 100 columns for tabular; INV states the current guide is later [Inferred].",
   loc="INV(e) lines 92, 115; BR C7; A RN-3",
   src="usage-guide.md, faqs.md, release-notes.md; one re-read"),
  dict(k="pins", f="CK1 CK2 INV", c="a", p="L", fl="",
   item="Pins: the playbook is cited at 45908b48 (staging, R007 item 7) while HEAD 97338569 carries the same text; INV(f) pins spaCy release-v3.8.16, spacy-models ca6f473a, Presidio 2.2.364, PyCryptodome v3.24.0 need confirming as the latest tags (README rule 8).",
   loc="CK1 R3 A:48, R4 A:69; CK2 R1 B:17; INV(f) lines 123-126",
   src="git ls-remote --tags (R013, R015); blob URLs already carry the refs (checker 0/0)"),
  dict(k="urls", f="CK1 CK2 CK3 INV", c="a", p="M", fl="",
   item="URLs and HTTP facts for P9: R9 and Source cells hold URLs that will not return a plain 200: cloak-api-guide and cloak-api-specifications-openapi (login redirect), cloak-anonymiser-package-guide, www.cloak.gov.sg/packages (307), go.gov.sg links (302), and the Presidio tutorial URL (HTTP 404, used as a Source URL in INV(d) and INV(f)); C8 (home page decryption link 404) and C9 (FAQ Terms link 404) are recorded as HTTP facts.",
   loc="CK1 R9 A:174-175; CK2 R9 B:166; CK3 R9 B:312; INV(d) line 82, INV(f) line 124, INV(a) line 18, INV(b) lines 29, 33-34; BR C8, C9; INV-RN 4",
   src="gr-url-checker; keep the login and redirect pages as documented HTTP facts with an exceptions list; replace the 404 tutorial URL in Source cells or note it as the HTTP fact"),
 ]),
 ("Style, process language and hygiene", [
  dict(k="proc", f="CK1 CK2 CK3 INV", c="a", p="M", fl="",
   item="Process and session language in deliverable text (finals must be clean): \"No access was requested and nothing was run ... during this research\", \"not interpreted here\", \"read with pypdf\" or \"via pypdf\", \"research is read-only\", \"were not opened\", \"(read-only rule)\", \"open at CP1\", \"not mined ... scope decision for Cloak research\", \"not reconciled here\", \"carry no interpretation\", \"(clauses read as written; needs GovTech's answer before any bench run)\".",
   loc="CK1 R7 A:125, R8 A:129, A:109, A:120; CK2 R7 B:116, B:122, R8 B:126; CK3 R7 B:272, B:278, R8 B:282; INV scope (line 3), lines 17, 19, 33, 87, 103, 114",
   src="README section 4 (finals contain no process language); mechanical grep in this triage; merger rewrites as product-neutral statements"),
  dict(k="ckids", f="CK1 INV", c="a", p="M", fl="",
   item="Internal ids in column text: \"(CK2 mechanisms)\", \"a CK3 mechanism\", \"CK1 to CK3\"; cross-references must use the exact header text (CK2 R1 B:18 does).",
   loc="CK1 R1 A:13, R3 A:50, R4 A:62-63, R6 A:102, A:107; INV scope (line 3)",
   src="README \"Headers and IDs\": a header is identical in every file; ids are internal"),
  dict(k="presxref", f="CK2 CK3", c="a", p="M", fl="",
   item="Cross-reference limit: the brief allows at most one Presidio cross-reference bullet per row (R4 and R8 mainly) and no restating of Presidio facts. CK3 R4 has three, and B:221 and B:233 state a Presidio token-layout fact; CK2 R4 B:73 states that Presidio has regex and word-list recognisers.",
   loc="CK3 R4 B:221, B:232-233, R2 B:199, R7 B:277; CK2 R4 B:73, R7 B:121",
   src="Brief \"Cross-reference, do not duplicate\"; keep one bullet per row, point to the Presidio header, drop restated facts"),
  dict(k="multif", f="CK1 CK3", c="a", p="L", fl="",
   item="Bullets with more than one fact under one label (README rule 5): A:64 (three release facts), A:98 (Mask defaults and Alias), B:232 (a quote plus an HTTP 404), A:105 (levels plus onboarding).",
   loc="CK1 R4 A:64, R6 A:98, A:105; CK3 R4 B:232",
   src="Mechanical split by the merger"),
  dict(k="legend", f="INV", c="a", p="L", fl="",
   item="INV short names used but not defined in the scope paragraph: TECHI, SAMPD, PRESTR, PRESENT, PRESENC.",
   loc="INV(d) intro (line 71), INV(c) lines 59, 67, INV(d) line 82, INV(f) line 124",
   src="README section 5 (short names defined once)"),
  dict(k="rn", f="CK3", c="a", p="L", fl="",
   item="B RN-2 says the anonymise-side and restore-side bullets are separate in R1, R3, R4, R5 and R6; R4 has none (side labels appear in R1, R3, R5 and R6 only: 13 anonymise-labelled, 10 restore-labelled bullets of 83 in R1 to R7).",
   loc="B RN-2; CK3 R2, R4, R7",
   src="Reviewer-note accuracy; matters if CP1-2 chooses a split (cost of splitting)"),
 ]),
]
