from gen_common import *
HE = ["Item","Value","Applies to","Source URL"]
SUBJ = "The page says quotas and limits are subject to change [Documented] (LIM)"
ROWS_E = [
["Maximum size of each request, except image.redact","0.5 MB [Documented] (LIM). Larger files should go to Cloud Storage and an inspection job [Documented] (LIM)","content.inspect, content.deidentify, content.reidentify",urls("limits")],
["Maximum size of each image.redact request","4 MB [Documented] (LIM)","image.redact",urls("limits")],
["Maximum findings per request","3,000 [Documented] (LIM). In an InspectContentRequest the maximum is the value set or 3,000, whichever is lower [Documented] (REST InspectConfig). More than 3,000 findings in a de-identification request returns Too many findings to de-identify; the findings returned are an arbitrary subset [Documented] (DOCS deidentify-sensitive-data)","content.inspect, content.deidentify",urls("limits","rinspcfg","deid")],
["Maximum table values per request","50,000 [Documented] (LIM, REST ContentItem)","Table items in content methods",urls("limits","ritem")],
["Maximum conversation messages per request","50k [Documented] (REST ContentItem). Same wording in the Python types [Documented: repo googleapis/google-cloud-python@google-cloud-dlp-v3.40.0] (types/dlp.py Conversation)","Conversation items (added 2026-06-03)",urls("ritem","r_types","relnotes")],
["Maximum transformations per request","100 [Documented] (LIM)","content.deidentify, content.reidentify",urls("limits")],
["InfoType and custom detector counts per request","150 built-in and custom infoTypes; 30 custom infoTypes; 10 regular custom dictionaries; 5 detection rules per custom infoType; 10 rule sets per inspection configuration; 10 rules per set; regular expression length 1000 [Documented] (LIM)","Inspection configuration of content methods",urls("limits")],
["Custom dictionary size","Word list passed in the request 128 KB per regular dictionary; word list from Cloud Storage 512 KB per regular dictionary; 5 MB combined for all stored custom dictionaries per request; 40 components per phrase [Documented] (LIM)","Custom dictionaries and stored infoTypes",urls("limits")],
["Maximum size of each quote","4 KB, a contextual snippet returned with findings [Documented] (LIM)","Content inspection with includeQuote, and storage inspection",urls("limits")],
["Resources per project","1000 templates; 1000 job triggers; 1000 running jobs; 30 stored infoTypes; 100 discovery configurations [Documented] (LIM)","Templates, jobs, stored infoTypes, discovery",urls("limits")],
["Requests per minute in total","10,000 across all global and regional endpoints and locations [Documented] (LIM). "+SUBJ,"All Sensitive Data Protection requests of a project",urls("limits")],
["Requests per minute to the global endpoint with a location specified","600 per minute per region [Documented] (LIM; the table repeats the quota name Number of requests to a regional endpoint per minute per region for this row and the next, and tells them apart by the description)","Requests to dlp.googleapis.com that name a location",urls("limits")],
["Requests per minute to a regional endpoint","100 per minute per region [Documented] (LIM)","Requests to dlp.REGION.rep.googleapis.com",urls("limits","endpoints")],
["Content policy file limits","PDF 50 MB; Word 30 MB; PowerPoint 30 MB; Excel 30 MB; plain text or image file 10 MB; the verdict for oversize files is configurable [Documented] (LIM). Content policy price: no row on the pricing page [Not disclosed] (checked PRC). The Gemini Enterprise page says there is no additional cost to use Sensitive Data Protection there [Documented] (Gemini Enterprise docs, not SDP docs)","Content policies",urls("limits","pricing","gemini")],
["Content method prices","Inspection: first gibibyte per month per account free, then $3.00 per gibibyte up to 1 tebibyte, then $2.00. Transformation: first gibibyte free, then $2.00, then $1.00 above 1 tebibyte. Minimum 1 KB billed per request. Simple redaction (RedactConfig and ReplaceWithInfoTypeConfig) is not counted as transformed bytes when infoType inspection is configured [Documented] (PRC). image.redact bills inspection only; deidentify and reidentify bill both [Documented] (PRC)","content.inspect, content.deidentify, content.reidentify, image.redact",urls("pricing")],
["Availability SLO","99.5% monthly uptime for content.inspect and content.deidentify, 99% in the Mexico and Stockholm regions [Documented] (SLA). No row for content.reidentify or image.redact [Not disclosed] (checked the SLA page). No SLO guaranteed for jobs and job triggers [Documented] (DOCS concepts-job-triggers)","content.inspect, content.deidentify; jobs",urls("sla","jobtrig")],
]
assert len(ROWS_E)==16, len(ROWS_E)
