from gen_common import *
HDD = ["Path","Access method","Auth","Regional options","Applies to (prompt, response, both or not AI)","Notes","Covered by Table 3 column","Source URL"]
ALL6 = cov("SD1","SD2","SD3","SD4","SD5","SD6")
BOTH = "Both, plus retrieved text and tool data: the caller sends any string or image bytes and no direction flag exists [Inferred] (premise: ContentItem has no direction field)"
AUTH = "OAuth bearer token, for example from gcloud auth print-access-token, or a service account holding roles/dlp.user [Documented] (DOCS inspect-sensitive-text-api, DOCS auth). A console API key works for all projects.content.* and projects.image.* methods, but not with a Cloud KMS wrapped key on deidentify or reidentify [Documented] (DOCS auth)"
ROWS_D = [
["REST global endpoint",
 "HTTPS to dlp.googleapis.com, for example POST /v2/projects/PROJECT_ID/content:inspect [Documented] (DOCS api-endpoints, DOCS inspect-sensitive-text-api)",
 AUTH,
 "No location in the path means the global region; a location in the path means processing in that region or multi-region, with no guarantee that in-transit data stays there [Documented] (DOCS api-endpoints)",
 BOTH,
 "Quota 10,000 requests per minute in total and 600 per minute per region when a location is specified [Documented] (DOCS limits). The global endpoint terminates TLS as close to the client as possible [Documented] (DOCS api-endpoints). The product is now part of Sensitive Data Protection but the API name remains Cloud Data Loss Prevention API [Documented] (DOCS overview)",
 ALL6, urls("endpoints","inspapi","auth","limits")],
["REST regional endpoint",
 "HTTPS to dlp.REGION.rep.googleapis.com, for example dlp.us-west1.rep.googleapis.com [Documented] (DOCS api-endpoints)",
 "Same credentials as the global endpoint [Inferred] (premise: the docs describe one API with two endpoint types)",
 "Regional endpoints guarantee that data at rest, in use and in transit is not moved out of the location, excluding Service Data [Documented] (DOCS api-endpoints). asia-southeast1 (Singapore) supports regional endpoints; the asia multi-region does not [Documented] (DOCS locations)",
 BOTH,
 "Quota 100 requests per minute per region [Documented] (DOCS limits). The docs say regional endpoint quotas are lower than the other two quota sets [Documented] (DOCS api-endpoints). The console cannot use regional endpoints, so the API is needed [Documented] (DOCS specifying-location)",
 ALL6, urls("endpoints","locations","specloc","limits")],
["Python client library (google-cloud-dlp 3.40.0)",
 "pip package google-cloud-dlp; sync and async clients with gRPC, async gRPC and REST transports [Documented: repo googleapis/google-cloud-python@google-cloud-dlp-v3.40.0] (services/dlp_service and transports directory listing). Methods include inspect_content, deidentify_content, reidentify_content, redact_image and list_info_types [Documented: repo googleapis/google-cloud-python@google-cloud-dlp-v3.40.0] (client.py)",
 "Application Default Credentials, set up with gcloud auth application-default login for local use [Documented] (DOCS libraries)",
 "Not stated for the Python library [Not disclosed] (checked the libraries page and the package README at the tag)",
 BOTH,
 "Release 3.40.0 dated 2026-10-01, Apache License 2.0, python_requires >=3.10, google-api-core[grpc] >=2.28.0 and <3.0.0 [Documented: repo googleapis/google-cloud-python@google-cloud-dlp-v3.40.0] (CHANGELOG.md, LICENSE, setup.py). The libraries page tells Python users to install samples requirements and says samples work with Python 2.7.x and 3.4 and higher, which is older than setup.py [Documented] (DOCS libraries). The generated client proves the API surface, not server behaviour [Inferred] (premise: it is generated gRPC and proto code). The older googleapis/python-dlp repository is reported archived with its contents moved to google-cloud-python [To be verified] (exploration note only; the GitHub page returned HTTP 403 on 2026-10-09 and the archive notice was not re-read)",
 ALL6, urls("libs","r_client","r_transports","r_setup","r_changelog","r_license")],
["Other client libraries",
 "C# (Google.Cloud.Dlp.V2), Go (go get cloud.google.com/go/dlp), Java (google-cloud-dlp, libraries-bom 26.90.0), Node.js (npm install @google-cloud/dlp), PHP (composer require google/cloud-dlp, needs the gRPC extension), Ruby (gem install google-api-client) [Documented] (DOCS libraries)",
 "Application Default Credentials [Documented] (DOCS libraries)",
 "Not stated per library [Not disclosed] (checked the libraries page)",
 BOTH,
 "The other libraries were not read at a pinned ref [Not disclosed] (only the libraries page was read). The Ruby line installs google-api-client, which the page describes as the older Google API Client Libraries family [Inferred] (premise: the page contrasts the Cloud Client Libraries with the older Google API Client Libraries)",
 ALL6, urls("libs")],
["Cloud console, gcloud CLI and web demo",
 "The console manages jobs, job triggers, discovery, templates and content policies [Documented] (DOCS concepts-method-types, DOCS manage-content-policies). The gcloud CLI is used in the docs to enable the API, log in and print access tokens [Documented] (DOCS inspect-sensitive-text-api). A dedicated gcloud command group for content inspection [Not disclosed] (checked the method-types and inspect-text API pages). The docs navigation lists a web-based inspection demonstration app at cloud.google.com/dlp/demo, which returned HTTP 200 and the title Sensitive Data Protection Demo on 2026-10-09 [Documented]",
 "Console sign-in with a Google account [Inferred] (premise: console access needs a Google Cloud project role)",
 "Regional endpoints are not available for use with the console [Documented] (DOCS specifying-location)",
 "Not AI by itself: manual use and administration [Inferred] (premise: these are administrator and demo tools). What the demo app does with entered text [To be verified] (not exercised, read-only rule)",
 "Not signed in to or run for this sheet. The demo page may help a quick manual test but its data handling is unknown [To be verified]",
 MK, urls("methods","inspapi","specloc","demo")],
["Model Armor basic mode",
 "Model Armor template with a sensitive-data filter in basic configuration, calling Sensitive Data Protection for inspection only [Documented] (Model Armor docs, not SDP docs). The Model Armor sensitive-data columns cover this path",
 "Model Armor's own access model; covered by the Model Armor columns",
 "Covered by the Model Armor columns",
 "Both: Model Armor filters prompts and responses [Documented] (Model Armor docs, not SDP docs)",
 "An integration path into SDP, not an SDP function. Basic mode does not use SDP templates [Documented] (Model Armor docs, not SDP docs). No internals are repeated here",
 MK, urls("ma_overview","ma_sanitize")],
["Model Armor advanced mode",
 "Model Armor template that references an SDP inspect template and optionally a de-identify template [Documented] (Model Armor docs, not SDP docs). Advanced configuration supports both inspection and de-identification [Documented] (Model Armor docs, not SDP docs)",
 "Model Armor's own access model; covered by the Model Armor columns",
 "The Model Armor template names the SDP templates by full resource name under projects/PROJECT_ID/locations/LOCATION [Documented] (Model Armor docs, not SDP docs)",
 "Both: Model Armor filters prompts and responses [Documented] (Model Armor docs, not SDP docs)",
 "An integration path into SDP, not an SDP function. The SDP inspection and de-identify templates themselves are inventory rows in block (a). No internals are repeated here",
 MK, urls("ma_overview","ma_sanitize","templates")],
["Gemini Enterprise content-policy attachment",
 "A content policy applied to Gemini Enterprise connectors (third-party, Google Workspace, custom MCP servers), metadata labels and file uploads to the assistant and notebooks [Documented] (Gemini Enterprise docs, not SDP docs)",
 "The Gemini Enterprise service account needs roles/dlp.user, and the administrator needs the Gemini Enterprise Admin role [Documented] (Gemini Enterprise docs, not SDP docs; DOCS manage-content-policies)",
 "Global, EU and US multi-regions [Documented] (Gemini Enterprise docs, not SDP docs)",
 "Neither prompt nor response: it guards inbound sources, and Model Armor guards the serving path [Documented] (Gemini Enterprise docs, not SDP docs)",
 "Supported in all Gemini Enterprise editions except Business, with no additional cost stated for Sensitive Data Protection [Documented] (Gemini Enterprise docs, not SDP docs). Not applied to older data stores such as Cloud Storage, BigQuery or websites [Documented] (Gemini Enterprise docs, not SDP docs)",
 MK, urls("gemini","managecp","cpolicy")],
["Apigee",
 "Apigee Edge Google Cloud Data Loss Prevention Extension 1.2.0, called through an ExtensionCallout policy with the actions deidentifyWithMask, deidentifyWithType and redactImage [Documented] (Apigee docs, not SDP docs)",
 "A service account key JSON supplied when configuring the extension [Documented] (Apigee docs, not SDP docs)",
 "Not stated [Not disclosed] (checked the extension page)",
 "Either: it acts on API proxy request or response content; AI traffic is not mentioned [Not disclosed] (checked the extension page)",
 "The page carries the caution This version of the extension is no longer supported and has been deprecated, and says extensions are available to Google Cloud Apigee customers with an Enterprise support plan [Documented] (Apigee docs, not SDP docs). The SDP docs navigation still links to it [Documented] (DOCS overview)",
 cov("SD3","SD5"), urls("apigee","overview")],
["Cloud Data Fusion",
 "A Sensitive Data Protection plugin with PII Filter, Redact and Decrypt transforms, for instances on Data Fusion version 6.1.1 or higher [Documented] (Cloud Data Fusion docs, not SDP docs)",
 "The DLP Administrator role on the cluster or Wrangler service account [Documented] (Cloud Data Fusion docs, not SDP docs)",
 "Not stated [Not disclosed] (checked the Data Fusion page)",
 "Not AI: data pipeline transforms [Inferred] (premise: the page describes filtering, masking or decrypting pipeline records)",
 "The plugin is based on the Cloud Data Loss Prevention API and follows its quotas and usage limits [Documented] (Cloud Data Fusion docs, not SDP docs)",
 MK, urls("datafusion")],
["BigQuery at query time",
 "BigQuery remote functions backed by a Cloud Run service that calls Sensitive Data Protection de-identification templates [Documented] (DOCS deidentify-bq-tutorial)",
 "Roles and service accounts are set in the tutorial steps [To be verified] (not read in detail)",
 "Not stated [Not disclosed] (checked the tutorial)",
 "Not AI: SQL queries over warehouse data [Inferred] (premise: the tutorial targets analysts running SQL)",
 "Encrypts and decrypts free text within a SQL query result [Documented] (DOCS deidentify-bq-tutorial). Uses content methods for the transformation [Inferred] (premise: it calls de-identification templates from a service)",
 MK, urls("bqtut")],
["Storage-side actions (Cloud Storage, Pub/Sub, Data Catalog, Security Command Center)",
 "Actions on inspection jobs that save findings to BigQuery, publish to Pub/Sub, send results to Data Catalog or send results to Security Command Center [Documented] (DOCS inspecting-storage, DOCS overview). Discovery can publish profiles to Security Command Center and Pub/Sub and tag in Knowledge Catalog, the last marked Deprecated in the pricing action table [Documented] (DOCS data-profiles, DOCS pricing)",
 "Service agent roles for the job [Documented] (DOCS deidentify-storage)",
 "Job processing region follows the data and the template [Documented] (DOCS data-profiles, Data residency considerations)",
 "Not AI: storage-side reporting [Inferred] (premise: these actions follow storage jobs and discovery)",
 "None of these paths returns a verdict to a caller [Inferred] (premise: they are post-scan actions)",
 MK, urls("storage","profiles","pricing","deidstorage")],
["Dataflow, AWS S3 and JDBC guides",
 "The SDP navigation lists guides for AWS S3, JDBC databases and a Dataflow, BigQuery ML anomaly detection solution; the S3 guide links to a GoogleCloudPlatform GitHub sample and the JDBC guide to a community tutorial [Documented] (DOCS overview, navigation). The linked pages were not read: the GitHub sample page returned HTTP 403 on 2026-10-09 and the community tutorial is not an SDP docs page [Documented]",
 "Not read [To be verified]",
 "Not read [To be verified]",
 "Not AI by name: data migration and database scanning [Inferred] (premise: the guide titles refer to S3, JDBC and Dataflow)",
 "Whether any of these guides uses a content method on text that could be an AI prompt or response [To be verified] (not read, so no column is proposed)",
 MK, urls("overview")],
]
assert len(ROWS_D)==13, len(ROWS_D)
