from gen_common import *
HA = ["Component","Method or resource","Mode (synchronous or asynchronous)","Data stored in Google Cloud","Input types","In Table 3 scope?","Covered by Table 3 column","Source URL"]
ROWS_A = [
# 1 content.inspect
["Content inspection",
 "projects.content.inspect and projects.locations.content.inspect (POST content:inspect) [Documented] (REST root)",
 "Synchronous and stateless: content methods are described as synchronous, stateless methods [Documented] (DOCS concepts-method-types)",
 "No: the results of content methods and the image.redact method are not stored in Google Cloud [Documented] (DOCS overview). Request data is encrypted in transit and is not stored [Documented] (DOCS concepts-method-types)",
 "One ContentItem per request: a string, a table, a byte item, a conversation or a batch [Documented] (REST ContentItem). Conversation support was added 2026-06-03 and batch support 2026-06-12 [Documented] (DOCS release-notes). The same five item kinds exist in the Python types at the tag [Documented: repo googleapis/google-cloud-python@google-cloud-dlp-v3.40.0] (types/dlp.py ContentItem)",
 "Yes: any string, table, conversation or image bytes can be sent, so prompts, responses, retrieved text and tool data are all possible; there is no input or output flag [Inferred] (premise: ContentItem has no direction field)",
 cov("SD1","SD2","SD5","SD6"),
 urls("restroot","ritem","methods","overview","relnotes","r_types")],
# 2 content.deidentify
["Content de-identification",
 "projects.content.deidentify and projects.locations.content.deidentify (POST content:deidentify) [Documented] (REST root)",
 "Synchronous and stateless, as for the other content methods [Documented] (DOCS concepts-method-types)",
 "No: results are returned in the response and are not stored in Google Cloud [Documented] (DOCS overview). Cloud KMS charges apply if a Cloud KMS key is used for cryptographic transformations [Documented] (DOCS transformations-reference)",
 "The same ContentItem kinds as content.inspect, plus a de-identification configuration or a template name [Documented] (REST deidentify). The response carries the de-identified item and a transformation overview [Documented: repo googleapis/google-cloud-python@google-cloud-dlp-v3.40.0] (types/dlp.py DeidentifyContentResponse). More than 3,000 findings returns the message Too many findings to de-identify [Documented] (DOCS deidentify-sensitive-data)",
 "Yes: masks or tokenises sensitive spans in any string before it goes to or comes from a model; no direction flag [Inferred] (premise: the docs name LLM prompts as a use case and the request has no direction field)",
 cov("SD3","SD4"),
 urls("restroot","rdeid","deid","methods","overview","r_types")],
# 3 content.reidentify
["Content re-identification",
 "projects.content.reidentify and projects.locations.content.reidentify (POST content:reidentify) [Documented] (REST root)",
 "Synchronous and stateless [Documented] (DOCS concepts-method-types)",
 "No: results are not stored in Google Cloud [Documented] (DOCS overview)",
 "A ContentItem previously de-identified with a reversible transformation, a re-identification configuration or template [Documented] (REST reidentify). The reversible transformations are CryptoDeterministicConfig and CryptoReplaceFfxFpeConfig only [Documented] (REST reidentify)",
 "Yes: reverses tokens in text that returns from a model or from storage; same undifferentiated item as the other content methods [Inferred] (premise: it accepts the same ContentItem)",
 cov("SD4"),
 urls("restroot","rreid","methods","overview")],
# 4 image.redact
["Image redaction",
 "projects.image.redact and projects.locations.image.redact (POST image:redact) [Documented] (REST root)",
 "Synchronous and stateless [Documented] (DOCS concepts-method-types)",
 "No: results of the image.redact method are not stored in Google Cloud [Documented] (DOCS overview)",
 "Image bytes, request limit 4 MB [Documented] (DOCS limits). The REST reference says the content must be PNG, JPEG, SVG or BMP [Documented] (REST redact). The redaction guide says content redaction is not supported for SVG, PDF, XLSX, PPTX or DOCX files [Documented] (DOCS redacting-sensitive-data-images). The supported-file-types table lists bmp, gif, jpe, jpeg, jpg and png for images [Documented] (DOCS supported-file-types). These three statements conflict; only the first frame of a multiframe image is redacted [Documented] (REST redact)",
 "Yes: images sent to or from a model; image bytes only, no direction flag [Inferred] (premise: the request carries only image bytes and a configuration)",
 cov("SD5","SD6"),
 urls("restroot","rredact","redactimg","filetypes","methods","overview","limits")],
# 5 content policies
["Content policies",
 "projects.locations.contentPolicies with create, delete, get, list and patch; no evaluation method is listed on the resource page or in the REST root [Documented] (REST contentPolicies, REST root). The Python client has create_content_policy, update_content_policy, get_content_policy, list_content_policies and delete_content_policy and no evaluation method [Documented: repo googleapis/google-cloud-python@google-cloud-dlp-v3.40.0] (client.py). An evaluation method outside the public REST and client surface [Not disclosed] (checked REST root, contentPolicies page, content-policy and manage pages, client.py at the tag)",
 "The overview promises immediate, synchronous verdicts [Documented] (DOCS content-policy). The call that submits content for a verdict is not exposed [Not disclosed] (checked the same pages). IAM has a permission dlp.contentPolicies.apply and a role DLP Content Policies Consumer, described as Apply content policies [Documented] (DOCS roles-permissions); an apply operation exists somewhere in the service [Inferred] (premise: a permission with that name is defined)",
 "The policy resource is stored in the region or multi-region the administrator selects [Documented] (DOCS manage-content-policies). Optional logging of policy outcomes to a BigQuery table [Documented] (DOCS content-policy). Whether evaluated content is stored [Not disclosed] (checked the content-policy and manage pages)",
 "Content in Gemini Enterprise connectors (third-party, Google Workspace, custom MCP servers), metadata labels and assistant or notebook file uploads [Documented] (Gemini Enterprise docs, not SDP docs). The documented use cases also name blocking chatbot responses and a verdict on AI model training data [Documented] (DOCS content-policy). GA since 2026-08-31 [Documented] (DOCS release-notes)",
 "Partly: it returns a real ALLOW or BLOCK verdict, but no documented way to submit an arbitrary test string was found [Inferred] (premise: the evaluation call is not in the REST resource or the client)",
 cov("MK"),
 urls("rcp","cpolicy","managecp","roles","gemini","relnotes","r_client")],
# 6 storage inspection job
["Storage inspection job",
 "projects.dlpJobs.create with a storage configuration, and the dlpJobs resource methods [Documented] (REST root, DOCS concepts-method-types)",
 "Asynchronous: a managed job; the docs name the DlpJob as the way to inspect data at rest asynchronously [Documented] (DOCS sensitive-data-protection-overview)",
 "Yes: job details (status, bytes scanned, summary findings per infoType) are stored, and the results of inspection and hybrid jobs are stored in Google Cloud [Documented] (DOCS concepts-method-types, DOCS overview). Optional actions can save findings to BigQuery or publish to Pub/Sub [Documented] (DOCS overview)",
 "Cloud Storage buckets and folders, BigQuery tables and Datastore kinds; Cloud Storage files can be binary, text, image, Word, Excel, PowerPoint, PDF and Avro [Documented] (DOCS inspecting-storage)",
 "No: scans stored data, not prompts or responses [Inferred] (premise: the input is a storage location, not a request payload)",
 cov("MK"),
 urls("methods","overview","storage","restroot")],
# 7 hybrid
["Hybrid inspection (job and job trigger)",
 "projects.dlpJobs (hybrid job), projects.jobTriggers and the hybridInspect request [Documented] (DOCS concepts-hybrid-jobs, REST root)",
 "Asynchronous: hybrid methods are asynchronous and do not return inspection results in the API response [Documented] (DOCS concepts-method-types)",
 "Yes: findings are stored in Google Cloud on the job resource and can go to BigQuery, email or Pub/Sub [Documented] (DOCS concepts-hybrid-jobs)",
 "Payloads of data sent from virtually any source, with optional metadata labels [Documented] (DOCS concepts-hybrid-jobs). One listed scenario monitors network traffic with a Sensitive Data Protection Filter for Envoy, described as a WebAssembly HTTP filter for Envoy sidecar proxies [Documented] (DOCS concepts-hybrid-jobs); whether that filter is meant for AI traffic [Not disclosed] (checked the hybrid page)",
 "No by default: findings are not returned to the caller, so the path cannot gate a prompt or response [Inferred] (premise: results are stored and processed server-side asynchronously)",
 cov("MK"),
 urls("hybrid","methods","restroot")],
# 8 de-identification in storage
["De-identification in storage",
 "An inspection job (DlpJob) configured to write de-identified copies of Cloud Storage files [Documented] (DOCS concepts-deidentify-storage)",
 "Asynchronous: runs as an inspection job [Documented] (DOCS concepts-deidentify-storage)",
 "Yes: de-identified copies go to a separate Cloud Storage bucket, and transformation details can be written to a BigQuery table [Documented] (DOCS concepts-deidentify-storage, DOCS deidentify-storage)",
 "Cloud Storage files of the CSV, image, text and TSV groups [Documented] (DOCS concepts-deidentify-storage). Maximum file size 60,000 KB [Documented] (DOCS limits)",
 "No: bulk files at rest, not the AI conversation [Inferred] (premise: the input is a bucket)",
 cov("MK"),
 urls("deidconc","deidstorage","limits")],
# 9 discovery
["Discovery and data profiles",
 "DiscoveryConfig resources (projects and organizations .locations.discoveryConfigs) and the data profile resources [Documented] (DOCS concepts-method-types, REST root)",
 "Asynchronous and continuous: discovery runs on the scope and frequency in the configuration [Documented] (DOCS concepts-method-types)",
 "Yes: generated profiles are stored (the docs point to a data residency section for where) and can be sent to Security Command Center or exported to BigQuery [Documented] (DOCS concepts-method-types, DOCS data-profiles)",
 "BigQuery, Cloud SQL, Cloud Storage and Vertex AI; other clouds with a Security Command Center Enterprise activation [Documented] (DOCS concepts-method-types)",
 "No: profiles data repositories, not the AI conversation [Inferred] (premise: the inputs are repositories)",
 cov("MK"),
 urls("methods","profiles","restroot")],
# 10 risk analysis
["Re-identification risk analysis job",
 "projects.dlpJobs.create with KAnonymityConfig, LDiversityConfig or KMapEstimationConfig; the concepts page also lists delta-presence [Documented] (DOCS pricing, DOCS concepts-risk-analysis)",
 "Asynchronous: a DlpJob; the results of a DlpJob are stored in Google Cloud [Documented] (DOCS sensitive-data-protection-overview)",
 "Yes: job results are stored in Google Cloud [Documented] (DOCS sensitive-data-protection-overview). Risk analysis uses BigQuery resources and charges appear as BigQuery usage [Documented] (DOCS pricing)",
 "Structured BigQuery data [Documented] (DOCS sensitive-data-protection-overview)",
 "No: measures dataset re-identification risk, unrelated to prompts or responses [Inferred] (premise: the input is a BigQuery table)",
 cov("MK"),
 urls("risk","overview","pricing")],
# 11 job triggers
["Job triggers",
 "projects.jobTriggers with activate, create, delete, get, list and patch [Documented] (REST root)",
 "Asynchronous: a trigger creates jobs on a schedule of 1 to 60 days [Documented] (DOCS concepts-job-triggers)",
 "Yes: the trigger resource and the jobs it creates are stored; up to 1000 job triggers per project [Documented] (DOCS concepts-job-triggers, DOCS limits)",
 "Google Cloud storage repositories (Cloud Storage buckets, BigQuery tables, Datastore kinds), or hybrid payloads for a hybrid trigger [Documented] (DOCS concepts-job-triggers, DOCS concepts-hybrid-jobs)",
 "No: scheduled scans of stored data [Inferred] (premise: the trigger creates storage inspection jobs)",
 cov("MK"),
 urls("jobtrig","hybrid","limits","restroot")],
# 12 inspection template
["Inspection template",
 "projects.inspectTemplates (create, delete, get, list, patch) and organisation-level equivalents; the object is InspectTemplate [Documented] (REST root, DOCS concepts-templates)",
 "Not applicable: a stored configuration used by synchronous content calls and by jobs [Documented] (DOCS concepts-templates)",
 "Yes: the template is a stored resource; up to 1000 templates per project [Documented] (DOCS limits)",
 "An InspectConfig (infoTypes, likelihood, custom detectors) referenced by name in content.inspect, image.redact, jobs and discovery [Documented] (DOCS concepts-templates, REST inspect). Model Armor advanced mode also takes an SDP inspect template (Model Armor docs, not SDP docs) [Documented] (Model Armor docs)",
 "Yes: shared detection settings for prompts, responses and files [Inferred] (premise: templates can be used in content API calls)",
 cov("SD1"),
 urls("templates","rinspect","limits","ma_overview")],
# 13 deidentify template
["De-identification template",
 "projects.deidentifyTemplates (create, delete, get, list, patch) and organisation-level equivalents; the object is DeidentifyTemplate [Documented] (REST root, DOCS concepts-templates)",
 "Not applicable: a stored configuration used by synchronous content calls and by jobs [Documented] (DOCS concepts-templates)",
 "Yes: the template is a stored resource; up to 1000 templates per project [Documented] (DOCS limits)",
 "A DeidentifyConfig with infoType and structured-data transformations, referenced by name in content.deidentify and image.redact [Documented] (DOCS concepts-templates, REST deidentify). Model Armor advanced mode accepts an optional de-identify template (Model Armor docs, not SDP docs) [Documented] (Model Armor docs)",
 "Yes: shared masking settings for prompts, responses and files [Inferred] (premise: templates can be used in content API calls)",
 cov("SD3"),
 urls("templates","rdeid","limits","ma_overview")],
# 14 stored infoType
["Stored infoType (large custom dictionary)",
 "projects.storedInfoTypes and projects.locations.storedInfoTypes [Documented] (REST root)",
 "Asynchronous build, then used in synchronous requests: Sensitive Data Protection generates dictionary files when the stored infoType is created [Documented] (DOCS creating-stored-infotypes); referenced in an inspection configuration as a storedType [Documented] (DOCS creating-custom-infotypes)",
 "Yes: the term list sits in Cloud Storage or a BigQuery column, and generated dictionary files are stored in Cloud Storage; up to 30 stored infoTypes per project [Documented] (DOCS creating-stored-infotypes, DOCS limits)",
 "A term list from a Cloud Storage text file or one BigQuery column, supporting tens of millions of terms [Documented] (DOCS creating-stored-infotypes, DOCS creating-custom-infotypes)",
 "Yes: a custom detector usable on any string [Inferred] (premise: custom infoType detectors apply to content requests)",
 cov("SD2"),
 urls("stored","custom","limits","restroot")],
# 15 infoTypes.list
["Built-in infoType listing",
 "infoTypes.list and locations.infoTypes.list (GET /v2/infoTypes) [Documented] (REST root)",
 "Synchronous [Inferred] (premise: a plain GET that returns a list)",
 "No customer content is sent; storage of the request [Not disclosed] (checked the listing page and REST root)",
 "Optional language code and a filter on which parts of the API support the infoType; defaults to supported_by INSPECT [Documented: repo googleapis/google-cloud-python@google-cloud-dlp-v3.40.0] (types/dlp.py ListInfoTypesRequest). The page says infoTypes.list lists all built-in infoTypes currently supported [Documented] (DOCS listing-infotypes)",
 "Yes: the live list of detectors that a test bench must read because the reference changes periodically [Inferred] (premise: the reference says new detectors are released periodically)",
 cov("SD1"),
 urls("listinfo","infotypes","restroot","r_types")],
]
