import json, collections
D = "https://docs.cloud.google.com/sensitive-data-protection/docs"
REPO = "https://github.com/googleapis/google-cloud-python/blob/google-cloud-dlp-v3.40.0/packages/google-cloud-dlp"
U = {
 "overview": D + "/sensitive-data-protection-overview",
 "methods": D + "/concepts-method-types",
 "infotypes": D + "/infotypes-reference",
 "cinfo": D + "/concepts-infotypes",
 "likelihood": D + "/likelihood",
 "custom": D + "/creating-custom-infotypes",
 "deid": D + "/deidentify-sensitive-data",
 "transf": D + "/transformations-reference",
 "pseudo": D + "/pseudonymization",
 "insptext": D + "/inspecting-text",
 "inspimg": D + "/inspecting-images",
 "redactimg": D + "/redacting-sensitive-data-images",
 "cimg": D + "/concepts-image-redaction",
 "ctext": D + "/concepts-text-redaction",
 "cpolicy": D + "/content-policy",
 "managecp": D + "/manage-content-policies",
 "filetypes": D + "/supported-file-types",
 "locations": D + "/locations",
 "endpoints": D + "/api-endpoints",
 "specloc": D + "/specifying-location",
 "libs": D + "/libraries",
 "relnotes": D + "/release-notes",
 "restroot": D + "/reference/rest",
 "ritem": D + "/reference/rest/v2/ContentItem",
 "rinspcfg": D + "/reference/rest/v2/InspectConfig",
 "rinspect": D + "/reference/rest/v2/projects.content/inspect",
 "rdeid": D + "/reference/rest/v2/projects.content/deidentify",
 "rreid": D + "/reference/rest/v2/projects.content/reidentify",
 "rredact": D + "/reference/rest/v2/projects.image/redact",
 "rcp": D + "/reference/rest/v2/projects.locations.contentPolicies",
 "limits": "https://docs.cloud.google.com/sensitive-data-protection/limits",
 "pricing": "https://cloud.google.com/sensitive-data-protection/pricing",
 "sla": "https://cloud.google.com/sensitive-data-protection/sla",
 "templates": D + "/concepts-templates",
 "jobtrig": D + "/concepts-job-triggers",
 "stored": D + "/creating-stored-infotypes",
 "risk": D + "/concepts-risk-analysis",
 "profiles": D + "/data-profiles",
 "storage": D + "/inspecting-storage",
 "hybrid": D + "/concepts-hybrid-jobs",
 "deidstorage": D + "/deidentify-storage",
 "deidconc": D + "/concepts-deidentify-storage",
 "bqtut": D + "/deidentify-bq-tutorial",
 "roles": D + "/access-control/roles-permissions",
 "auth": D + "/auth",
 "listinfo": D + "/listing-infotypes",
 "inspapi": D + "/inspect-sensitive-text-api",
 "demo": "https://cloud.google.com/dlp/demo",
 "apigee": "https://docs.apigee.com/api-platform/reference/extensions/google-cloud-data-loss-prevention/google-cloud-data-loss-prevention-extension-120",
 "datafusion": "https://cloud.google.com/data-fusion/docs/how-to/using-dlp",
 "ma_overview": "https://docs.cloud.google.com/model-armor/overview",
 "ma_sanitize": "https://docs.cloud.google.com/model-armor/sanitize-prompts-responses",
 "gemini": "https://docs.cloud.google.com/gemini/enterprise/docs/protect-sensitive-data",
 "r_client": REPO + "/google/cloud/dlp_v2/services/dlp_service/client.py",
 "r_types": REPO + "/google/cloud/dlp_v2/types/dlp.py",
 "r_setup": REPO + "/setup.py",
 "r_changelog": REPO + "/CHANGELOG.md",
 "r_license": REPO + "/LICENSE",
 "r_readme": REPO + "/README.rst",
 "r_transports": REPO + "/google/cloud/dlp_v2/services/dlp_service/transports/rest.py",
}
def urls(*keys): return " ; ".join(U[k] for k in keys)
HD = {
 "SD1": "Sensitive Data Protection: Sensitive-data detection in text (infoType inspection)",
 "SD2": "Sensitive Data Protection: Custom detectors and inspection rules (custom infoTypes)",
 "SD3": "Sensitive Data Protection: Sensitive-data masking and de-identification in text",
 "SD4": "Sensitive Data Protection: Reversible tokenisation and re-identification (AES-SIV and FPE)",
 "SD5": "Sensitive Data Protection: Sensitive-data detection and redaction in images",
 "SD6": "Sensitive Data Protection: Image safety classification (sexual and violent content)",
}
MK = "— (inventory only, not in Table 3)"
def cov(*ids):
    if ids == ("MK",): return MK
    return "; ".join(HD[i] for i in ids)
RL = "[Documented: repo googleapis/google-cloud-python@google-cloud-dlp-v3.40.0]"
