import re,os
def norm(s): return re.sub(r"\s+"," ",s.replace("’","'").replace("“",'"').replace("”",'"')).strip().lower()
T={f[:-4]:norm(open(f,encoding="utf-8",errors="replace").read()) for f in os.listdir(".") if f.endswith(".txt") and not f.startswith("err_")}
Q=[
("methods","Content methods are synchronous, stateless methods"),
("methods","Request data is encrypted in transit and is not stored"),
("methods","Hybrid methods are a set of asynchronous API methods"),
("methods","do not return inspection results in the API response"),
("overview","The results of content methods and the image.redact method aren't stored in Google Cloud"),
("overview","The API name remains the same: Cloud Data Loss Prevention API (DLP API)"),
("overview","The results of a DlpJob are stored in Google Cloud"),
("overview","The results of inspection and hybrid jobs are stored in Google Cloud"),
("deid","Too many findings to de-identify. Retry with a smaller request."),
("deid","The list of findings that Sensitive Data Protection returns is an arbitrary subset"),
("r_redact","The content must be PNG, JPEG, SVG or BMP."),
("r_redact","Only the first frame of each multiframe image is redacted"),
("redact_img","Content redaction is not supported for SVG, PDF, XLSX, PPTX, or DOCX files."),
("filetypes","bmp, gif, jpe, jpeg, jpg, png"),
("infotypes_ref","Not recommended for use during latency sensitive operations"),
("infotypes_ref","A unique set of nine alpha-numeric characters on the Singapore National Registration Identity Card."),
("infotypes_ref","API key used to authenticate requests to Anthropic APIs"),
("infotypes_ref","Image of a person's face. This infoType detector is in Preview."),
("infotypes_ref","analyze an entire image for sensitive or harmful subject matter"),
("infotypes_ref","when analyzing images, they first extract text from images and then analyze the text"),
("infotypes_ref","can classify documents into enterprise, sensitive, and regulated content categories"),
("infotypes_ref","These limited-availability infoTypes can cause scanning issues"),
("infotypes_ref","To get the latest list of built-in infoTypes, call the infoTypes.list method"),
("concepts_info","Country-specific infoTypes support the English language and the respective country's languages. Most global infoTypes work with multiple languages."),
("concepts_info","using various technologies, including natural language understanding"),
("concepts_info","you might flag most numeric and alphanumeric entities"),
("roles","Apply content policies."),
("roles","Inspect, Redact, and De-identify Content"),
("apigee","This version of the extension is no longer supported and has been deprecated."),
("apigee","Enterprise support plan"),
("apigee","deidentifyWithMask"),
("hybrid","Sensitive Data Protection Filter for Envoy (a WebAssembly HTTP filter for Envoy sidecar proxies)"),
("gemini","Sensitive Data Protection safeguards inbound data"),
("gemini","Model Armor safeguards the serving path"),
("gemini","There's no additional cost to use Sensitive Data Protection."),
("gemini","Sensitive Data Protection supports the global, EU, and US multi-regions."),
("gemini","Content policies don't apply to the older type of data store"),
("gemini","The Gemini Enterprise service account needs the DLP User (roles/dlp.user) role."),
("gemini","You need the Gemini Enterprise Admin role."),
("datafusion","version 6.1.1 or higher"),
("datafusion","based on the Cloud Data Loss Prevention API and therefore complies with the Sensitive Data Protection quotas and usage limits"),
("ma_overview","Basic configuration only supports inspection operations and doesn't support the use of Sensitive Data Protection templates."),
("ma_overview","Advanced configuration supports both inspection and de-identification operations."),
("ma_overview","Model Armor filters both input (prompts) and output (responses)"),
("auth","projects.content.* and projects.image.* methods"),
("auth","API keys can't be used for authentication"),
("endpoints","Regional endpoints guarantee data residency"),
("endpoints","There is no guarantee that the data in transit remains in the processing region"),
("endpoints","The quotas for regional endpoints are lower than the quotas for the other two."),
("specloc","regional endpoints for Sensitive Data Protection aren't available for use with the Google Cloud console"),
("locations","Image inspection and redaction are supported only in the following locations"),
("locations","Sensitive Data Protection scans those files as binary files"),
("locations","All Sensitive Data Protection features are accessible globally"),
("limits","Quotas and limits specified in this document are subject to change."),
("manage_cp","Select the region or multi-region where you want to store the content policy."),
("cpolicy","Get immediate, synchronous verdicts on content to enforce organizational data policies."),
("cpolicy","Get a verdict on whether to allow certain types of data in an AI model training dataset."),
("cpolicy","Automatically block chatbot responses or file uploads"),
("jobtrig_c","There are no service level objectives (SLO) guaranteed for jobs and job triggers."),
("jobtrig_c","Scheduled triggers run on an interval that you set, from 1 day to 60 days."),
("transf","Don't use the CryptoReplaceFfxFpeConfig method, except when preserving the input alphabet space and size is a requirement."),
("transf","The CryptoDeterministicConfig method has no limitations on the input and is much faster."),
("transf","radix^max_size <= 2^128."),
("transf","The input value is not encrypted but hashed."),
("transf","Replaces input values with a 32-byte hexadecimal string generated using a given data encryption key."),
("transf","Sensitive Data Protection outputs a base64-encoded representation of the hashed input value"),
("transf","Preserves sequence and duration"),
("transf","The bucketing transformations serve to de-identify numerical data"),
("pseudo","can't be re-identified"),
("pricing","A minimum of 1 KB is billed per content inspect or transform request."),
("pricing","Simple redaction, which includes the RedactConfig and ReplaceWithInfoTypeConfig transformations, is not counted against the number of bytes transformed when infoType inspection is also configured."),
("pricing","Risk analysis uses resources in BigQuery and charges appear as BigQuery usage."),
("sla","content.inspect API requests | >= 99.5%"),
("r_reid","This requires that only reversible transformations be provided here."),
("r_item","The maximum number of messages allowed is 50k."),
("r_inspcfg","the resulting maximum value is the value that you set or 3,000, whichever is lower."),
("relnotes","Added support for inspecting and de-identifying conversational content."),
("relnotes","Sensitive Data Protection content policies are in General Availability."),
("stored","Stored custom infoType detectors can match on up to tens of millions of") if False else ("custom","Stored custom infoType detectors can match on up to tens of millions of"),
("deid_conc","CSV Image Text TSV"),
("libs","Samples are compatible with Python 2.7.x and 3.4 and higher."),
("libs","pip install -r requirements.txt"),
("bqtut","remote functions"),
("hybrid","Hybrid jobs and job triggers encompass a set of asynchronous API methods"),
("profiles","continuously monitors"),
]
bad=0
for f,q in Q:
    if norm(q) not in T[f]:
        print("MISS",f,q); bad+=1
print("done",len(Q),"misses",bad)
