# -*- coding: utf-8 -*-
# Table content for NEW single-product groups (marker bullets are added by the generator).
G = {}

G["C30"] = dict(
 name="Document screening of uploaded files",
 funcs=["BB"],
 inputs=(["Suggested: PDF, CSV, text, Office files with planted injection, fake data, URLs",
          "One file per type, from 69 bytes to 4 MB",
          "Clean files as controls; synthetic content only"],
         ["BB R7","BB R6"]),
 truth=(["Suggested: per file, expected match for each enabled filter",
         "Planted items are known, so labels are deterministic",
         "Expected outcome for oversize or tiny files: skipped or rejected"],
        ["BB R2","BB R5"]),
 outputs=(["Per-filter result: execution state and match state",
           "URL positions only for plain text",
           "Skipped or rejected status; latency; error"],
          ["BB R5"]),
 metrics=(["Detection rate per filter and file type",
           "False-positive rate on clean files",
           "Skip and reject behaviour at the size limits",
           "Latency by file size"],
          ["BB R5","BB R6"]),
 arch=(["Suggested harness: file generator, base64 encoder, adapter, recorder, evaluator",
        "Model Armor template in a full-support region with the wanted filters",
        "Direct API prompt method, with the file type set by hand",
        "Model Armor user role"],
       ["BB R6","BB R7","3h (b) integration paths"]),
 diffs=(["Text extractor undisclosed; scans and layout handling unknown",
         "Embedded images in files are not screened, though one page says otherwise",
         "Only the direct API and Gemini Enterprise accept documents",
         "Response-side documents are undocumented",
         "Cloak (BL) and SDP (AN) also take files: not compared here",
         "Google AUP testing clause not recorded for BB: open item"],
        ["BB R2","BB R3","BB R4","BB R8","3h (b) integration paths"]),
)

G["C31"] = dict(
 name="Input-level malicious URL detection",
 funcs=["AZ"],
 inputs=(["Suggested: user prompts with known-bad and benign URLs",
          "Shortened, obfuscated, redirecting and URL-encoded links",
          "Prompts with more than 256 URLs; benign look-alike domains"],
         ["AZ R7","AZ R2"]),
 truth=(["Suggested: per URL, malicious or benign label",
         "Labels would need an independent URL reputation source: not chosen"],
        ["AZ R7","AZ R4"]),
 outputs=(["Match flag and matched URLs, with ranges for plain text",
           "Execution state; latency; error"],
          ["AZ R5"]),
 metrics=(["True-positive and false-positive rates per URL",
           "Behaviour past the 256-URL scan limit",
           "Latency per call"],
          ["AZ R5","AZ R2"]),
 arch=(["Suggested harness: prompt loader, adapter, recorder, evaluator",
        "Model Armor template with the URL filter on, in a full-support region",
        "Regional sanitize-user-prompt endpoint; no confidence setting exists"],
       ["AZ R7","AZ R6","3h (d) locations and feature availability"]),
 diffs=(["Reputation source and method are not disclosed",
         "On or off only; no confidence level",
         "Unavailable in limited-support regions with data residency enforced",
         "Only the first 256 URLs are scanned; encoded URLs not decoded",
         "Google AUP testing clause is an open item",
         "Response side is C32"],
        ["AZ R4","AZ R5","AZ R2","AZ R8","3h (d) locations and feature availability"]),
)

G["C32"] = dict(
 name="Output-level malicious URL detection",
 funcs=["BA"],
 inputs=(["Suggested: model responses with known-bad and benign URLs, scripted",
          "Shortened, obfuscated and URL-encoded links; streamed chunks",
          "Responses with more than 256 URLs"],
         ["BA R7","BA R8"]),
 truth=(["Suggested: per URL, malicious or benign label",
         "Labels would need an independent URL reputation source: not chosen"],
        ["BA R7","BA R4"]),
 outputs=(["Match flag and matched URLs, with ranges for plain text",
           "Execution state; latency; error"],
          ["BA R5"]),
 metrics=(["True-positive and false-positive rates per URL",
           "Behaviour past the 256-URL scan limit and across chunks",
           "Latency per call"],
          ["BA R5","BA R8"]),
 arch=(["Suggested harness: scripted responses, adapter, recorder, evaluator",
        "Model Armor template with the URL filter on, in a full-support region",
        "Regional sanitize-model-response endpoint"],
       ["BA R7","BA R6","3h (d) locations and feature availability"]),
 diffs=(["Same limits as C31: method undisclosed, on or off only",
         "Unavailable in limited-support regions with data residency enforced",
         "Docs examples send no user prompt",
         "Google AUP testing clause is an open item",
         "Input side is C31"],
        ["BA R4","BA R3","BA R8","3h (d) locations and feature availability"]),
)

G["C33"] = dict(
 name="Trace-level agent goal-hijacking detection",
 funcs=["BG"],
 inputs=(["Suggested: traces of one user request plus agent actions, half hijacked",
          "Indirect injection inside tool results that pushes the agent off-goal",
          "Legitimate but unusual actions as benign controls",
          "Synthetic traces suggested, since traces leave the machine"],
         ["BG R7","BG R2","BG R3"]),
 truth=(["Suggested: per action, aligned or hijacked relative to the user request",
         "Labels authored together with each trace"],
        ["BG R2","BG R7"]),
 outputs=(["Score 1.0 or 0.0; decision human-in-the-loop required or allow",
           "Never a block decision",
           "Latency; error; judge model reachability"],
          ["BG R5"]),
 metrics=(["True-positive and false-positive rates at the decision",
           "Judge stability across repeat runs",
           "Latency, context limits and Together cost per trace"],
          ["BG R5","BG R8"]),
 arch=(["Suggested harness building traces, with an assistant-role scanner",
        "llamafirewall on Python 3.10 or later",
        "Together API key and a judge model Together serves"],
       ["BG R6","BG R7","3j (b) LlamaFirewall scanner catalogue","3j (c) roles, use cases and default scanner map"]),
 diffs=(["Meta labels it experimental; figures are from Meta's own benchmark",
         "Code default model is listed as removed from Together serverless",
         "Model and endpoint cannot be set through the constructor",
         "Traces go to a third-party API; Together terms are an open item",
         "Not a content filter; treats doubtful actions as aligned"],
        ["BG R1","BG R4","BG R5","BG R6","BG R8","3j (f) licences, gating and terms"]),
)


G["C34"] = dict(
 name="Output-level insecure-code detection in model responses",
 funcs=["BH","BJ"],
 inputs=(["Suggested: scripted model outputs with insecure and benign code answers",
          "Possible seeds: CyberSecEval code prompts",
          "Benign code answers would be needed to test false positives"],
         ["BH R7","BJ R7","3k Reuse"]),
 truth=(["Suggested: per output, insecure or benign, with CWE class",
         "Independent labels would be needed; CyberSecEval ground truth is Code Shield itself"],
        ["BH R2","BJ R2","3k Reuse"]),
 outputs=(["BH: block or allow, score 1.0 or 0.0, issue list in reason",
           "BJ: insecure flag, issue list, block, warn or ignore",
           "Matched rule, CWE and line where given",
           "Latency; error"],
          ["BH R5","BJ R5"]),
 metrics=(["Detection rate per CWE class; false-positive rate on benign code",
           "Agreement between the scanner and the library on the same text",
           "Latency by language"],
          ["BH R5","BJ R5"]),
 arch=(["Suggested harness: scripted outputs, adapters, recorder, evaluator",
        "BH: llamafirewall with codeshield and Semgrep; BJ: pip codeshield and Semgrep",
        "No key, model or gated access for BH or BJ"],
       ["BH R7","BJ R7","3j (d) Code Shield language and analyzer matrix"]),
 diffs=(["BH runs the BJ engine: one engine through two surfaces",
         "BH scans whole messages; BJ takes a code string",
         "BH and BJ language lists conflict: seven or eight",
         "Code Shield is not a taint-flow analyser; Semgrep licence recorded",
         "NeMo O checked: it flags payloads, not coding practice"],
        ["BH R4","BH R3","BJ R3","BJ R2","BJ R8","O R2","3j (f) licences, gating and terms"]),
)
