# -*- coding: utf-8 -*-
# Table content for multi-product groups C9-C11, C13-C15 (C12 is carried over from v2 C6).
G = {}

G["C9"] = dict(
 name="Harmful-content classification of output (model responses)",
 funcs=["H","W","AA","AU","BD"],
 inputs=(["Suggested: model responses to benign and harmful prompts, scripted or generated",
          "Include safe refusals of unsafe prompts and benign near-misses",
          "H, W need the prompt; AA, BD, AU read the response alone",
          "NeMo moderation sample prompts can elicit responses; none are labelled",
          "Litmus Undesirable Content themes could guide cases; it publishes no prompts"],
         ["H R7","W R7","AA R3","AU R3","BD R3","3c Datasets","3n Reuse"]),
 truth=(["Suggested: per response, binary unsafe or safe label on the response itself",
         "Plus category label mapped to a common taxonomy",
         "Taxonomies: Nemotron codes, Llama Guard S1 to S14, LionGuard six, AU four",
         "Compare per category only where a mapping exists"],
        ["H R2","W R2","AA R2","AU R2","BD R2"]),
 outputs=(["Decision where exposed (H, W, AU overall match state)",
           "Category codes, per-category scores or probabilities (AA, BD, AU)",
           "First-token probability for W only if extracted",
           "Latency; error"],
          ["H R5","W R5","AA R5","AU R5","BD R5"]),
 metrics=(["True-positive, false-positive, false-negative rates on binary unsafe label",
           "Measured at each product's decision point",
           "AUPRC and sweeps: AA, BD, and W if probabilities extracted",
           "AU gives match states with confidence levels, no score",
           "Non-streaming runs only"],
          ["H R5","W R5","AU R5","BD R5","AA R5"]),
 arch=(["Suggested harness with scripted responses or a stub main LLM",
        "Also adapters, common result format, recorder, evaluator",
        "H: NeMo output rail with a safety model endpoint",
        "W: GPU-served Llama Guard with response template, verdict parser",
        "AA: Sentinel key; BD: local models; AU: regional response method"],
       ["H R7","3d (c) integration paths","3e (d) access paths","3i (c) dependencies and access","3h (b) integration paths","3c Tools"]),
 diffs=(["H with Nemotron prompts checks the user turn with the response",
         "W judges the response; AA, BD, AU read it alone",
         "So a harmful prompt can change the result",
         "Taxonomies differ; W reports no threshold: LG3, LG4 figures not comparable",
         "AA and BD share LionGuard models: not independent",
         "H blocks can follow streamed tokens",
         "AG excluded: Sentinel lists it input only",
         "AU docs examples send no prompt; Google AUP clause open item",
         "Sentinel is closed beta"],
        ["H R1","W R3","AA R3","AU R3","AU R8","H R2","W R5","3e (b) catalogue","AG R3","3e (d) access paths"]),
)

G["C10"] = dict(
 name="Input-level jailbreak and prompt-attack detection",
 funcs=["F","AB","AG","AV","BE","BF"],
 inputs=(["Suggested: single-turn jailbreak, injection and benign prompts",
          "Benign prompts that mention instructions or code; also non-English text",
          "Possible attack sources: Garak families; CyberSecEval injection cases, 251 English",
          "Benign look-alikes would be needed; Meta publishes none",
          "Litmus DoAnythingNow theme could guide jailbreak cases; no prompts published"],
         ["F R6","AB R7","AG R7","AV R7","BE R7","BF R7","3c Red-teaming","3k Datasets","3k Reuse","3n Reuse"]),
 truth=(["Suggested: per prompt, binary attack or benign label under one agreed definition",
         "Optionally with an attack style; CyberSecEval technique labels could help",
         "Definitions differ: F undefined; AB three intents; AV override and jailbreak",
         "BE flags explicit override only; AG jailbreak, injection, possibly leakage",
         "Garak labels come from its own detectors, some model-based"],
        ["F R2","AB R2","AG R2","AV R2","BE R2","3k Reuse","3c Tools"]),
 outputs=(["Decision: F block or allow; BE label; BF allow or block",
           "Scores: AB with confidence; AG, BE, BF; AV level; F none",
           "Latency; error, including detector-unreachable cases"],
          ["AB R5","AG R5","AV R5","BE R5","BF R5","F R5","F R4"]),
 metrics=(["True-positive, false-positive, false-negative rates at each product's decision point",
           "Recall at a fixed false-positive rate, as Meta reports for BE",
           "AUPRC and sweeps only for scored outputs: AB, BE, BF",
           "AG shows 0.0 and 1.0; AV gives levels; F has no score",
           "Latency; Garak reports protection rates per probe, not false positives"],
          ["AG R5","AV R5","BE R5","3c Red-teaming"]),
 arch=(["Suggested harness: loader, adapters, common result format, recorder, evaluator",
        "F: NeMo input rail with a detector (heuristics, or NemoGuard endpoint)",
        "BE: gated Hugging Face weights, Transformers; BF: llamafirewall PromptGuard scanner",
        "AB, AG: Sentinel beta key; AV: Google Cloud template, regional endpoint",
        "Garak NeMoGuardrails generator could drive F only"],
       ["F R7","BE R7","BF R7","AV R7","3e (d) access paths","3j (e) integration and access paths","3h (b) integration paths","3c Red-teaming","3c Engine coverage"]),
 diffs=(["BF runs the BE model: not independent",
         "Both need the Llama 4 licence gate",
         "Whether the Llama 4 policy allows attack-prompt testing is an open item",
         "AG is the aws/prompt_attack id, sharing the Bedrock backend with E",
         "AB model undisclosed; AV Google AUP clause open item",
         "F returns block or allow only, fails open, English-only heuristics",
         "BE has a 512-token limit and eight evaluated languages",
         "BI regex scanner holds two injection phrases: see C3",
         "NVIDIA garak, heuristic and Meta results are vendor-reported, not comparable"],
        ["BF R4","BE R8","BF R8","AG R2","AV R8","F R5","BE R6","BE R2","BI R2","3c Published results","3j (f) licences, gating and terms"]),
)

G["C11"] = dict(
 name="Prompt-injection detection in model output, tool output and retrieved text",
 funcs=["AW","BE","BF"],
 inputs=(["Suggested: tool results and retrieved passages, with and without injected instructions",
          "Scripted model replies carrying instructions or jailbreak text",
          "CyberSecEval has 55 indirect cases that could seed injected passages",
          "Benign tool text such as logs, JSON, web pages needed"],
         ["AW R7","BE R7","BF R7","BF R3","3k Datasets","3k Reuse"]),
 truth=(["Suggested: per text, injected or clean, under one agreed definition",
         "Direct or indirect label where seeded from CyberSecEval",
         "Definitions differ: AW names MCP tool errors; BE flags explicit override only"],
        ["AW R2","BE R2","BF R2"]),
 outputs=(["Match flag with confidence level (AW)",
           "Label with score (BE); allow or block with reason (BF)",
           "Latency; error"],
          ["AW R5","BE R5","BF R5"]),
 metrics=(["True-positive, false-positive, false-negative rates at each decision point",
           "AUPRC and sweeps only for scored outputs: BE, BF",
           "AW gives a confidence level, not a score",
           "Latency; BE and BF truncate beyond 512 tokens"],
          ["AW R5","BE R5","BF R5","BF R6"]),
 arch=(["Suggested harness submitting text on the tool, retrieval or response path",
        "AW: regional response method with a template, or gateway setting",
        "BF: llamafirewall with the TOOL role and PromptGuard scanner",
        "BE: gated weights loaded with Transformers; no service"],
       ["AW R7","BF R7","BE R7","3h (b) integration paths","3j (c) roles, use cases and default scanner map"]),
 diffs=(["AW scope conflicts: overview says responses, templates page says prompts only",
         "BF runs the BE model: not independent",
         "BE behaviour on tool and retrieved text is untested by Meta",
         "BE, BF on model replies: undocumented; Meta names user and tool text",
         "AW three-word rule for responses unknown; Google AUP clause open item",
         "Llama 4 licence gate and testing question open for BE, BF",
         "Hidden-character check is in C3; NeMo chunk filtering is C16"],
        ["AW R1","BF R4","BE R3","BF R3","BE R8","AW R8","BF R8","3j (f) licences, gating and terms"]),
)

G["C13"] = dict(
 name="Image content-safety classification of input (user-supplied images)",
 funcs=["X","AS"],
 inputs=(["Suggested: lawful, approved images labelled by category, with a fixed neutral text",
          "Real and AI-generated images; benign near-misses",
          "X needs a text part; AS takes image bytes only"],
         ["X R7","AS R7","X R6","AS R6"]),
 truth=(["Suggested: per image, safe or unsafe label from human review",
         "Harmonised subset: sexual content and violence; other categories reported apart",
         "Categories differ: X S1 to S13; AS three image categories"],
        ["X R2","AS R2","AS R7"]),
 outputs=(["First-line verdict and category codes (X)",
           "Likelihood bucket per finding (AS)",
           "Latency; error"],
          ["X R5","AS R5"]),
 metrics=(["True-positive, false-positive, false-negative rates at each decision point",
           "Per-category recall on the harmonised subset",
           "AS sweep over likelihood buckets; X has no score or threshold",
           "Latency per call"],
          ["X R5","AS R5","AS R7"]),
 arch=(["Suggested harness: image loader, adapters, label store, recorder, evaluator",
        "X: GPU host serving Llama Guard 4 or 3-11B-Vision, with processor",
        "AS: Google Cloud project, DLP API, image-scanning location such as Singapore",
        "AS request names the three image context detectors"],
       ["X R4","X R7","AS R7","AS R6","3d (a) variant table","3g (f) region and availability"]),
 diffs=(["X is not for image-only input; fixed neutral text is needed",
         "AS judges the whole image; X judges image and text together",
         "X judges request hazard; AS judges what the image shows",
         "Categories differ; AS models trained mainly on real-world images",
         "EU licence clause may apply to X",
         "AS on generated images has no comparator: X response side is C24",
         "Google AUP limits on explicit test images apply to AS",
         "AS accuracy and thresholds are open questions"],
        ["X R3","X R4","X R7","AS R1","AS R3","AS R4","AS R7","AS R8","X R8"]),
)

G["C14"] = dict(
 name="Sensitive-data detection and masking in tables and records",
 funcs=["AL","AN","AP"],
 inputs=(["Suggested: small tables with known PII columns and clean columns",
          "Cells with mixed content, odd column names and empty values",
          "JSON objects with known PII keys (AL only)",
          "Records could stand for retrieved rows or parsed tool output"],
         ["AL R7","AN R6","AP R6","AL R3"]),
 truth=(["Suggested: per cell, PII entity type or none",
         "Per table, expected column-to-entity map (AL; derived for AN)",
         "Expected masked table: PII cells changed, clean cells untouched",
         "Harmonised entity subset scored; other types reported apart"],
        ["AL R2","AL R5","AN R2","AP R5"]),
 outputs=(["Transformed table or object (AL, AP)",
           "AL column-to-entity map, no per-cell findings or scores",
           "AN findings with likelihood and position",
           "AP change summary; latency; error"],
          ["AL R5","AN R5","AP R5"]),
 metrics=(["Cell-level detection rate and false-positive rate on clean cells",
           "Column-map accuracy where a map exists (AL; derived for AN)",
           "Masking correctness per cell: PII changed, clean unchanged",
           "Latency and throughput on larger tables"],
          ["AL R7","AL R8","AN R5","AP R5"]),
 arch=(["Suggested harness: table loader, adapters, cell scorer, recorder, evaluator",
        "AL: presidio-structured package with the English spaCy model; no account",
        "AN, AP: Google Cloud project, DLP User role, table content item",
        "SDP request caps: 0.5 MB and 50,000 table values"],
       ["AL R7","AN R7","AP R7","3f (d) integration paths","3g (a) method and component catalogue","3g (e) limits, quotas and pricing"]),
 diffs=(["AL maps columns by sampling; AN, AP read each cell",
         "AL is alpha (0.0.8); SDP is a managed API",
         "No SDP column documents JSON input; AL does",
         "Table use is a content-item mode of AN, AP",
         "Free text inside cells is future work for AL",
         "AL shares Analyzer and Anonymizer backends with C1"],
        ["AL R1","AL R4","AL R2","AN R1","AP R1","AL R8","AN R3"]),
)
