# -*- coding: utf-8 -*-
# Table content for the new multi-product groups C1-C8 (bullets <= 12 words; refs are sheet 3 / inventory tags).
G = {}

G["C1"] = dict(
 name="Input-level PII and sensitive-data detection and masking in text",
 funcs=["E","K","AF","AH","AI","AN","AP","AX","BL"],
 inputs=(["Suggested: single user messages with synthetic, labelled PII of known types",
          "Add ambiguous strings, custom-format identifiers, Singapore-style IDs, non-PII controls",
          "NeMo ships no PII dataset; seed data would be built",
          "presidio-research is a possible scorer for span results"],
         ["E R6","K R7","AF R7","AH R7","AN R7","BL R7","3c Reuse"]),
 truth=(["Suggested: per text, PII type and character span of each item",
         "Expected action (block, mask or allow) and expected masked text",
         "Entity lists differ: a harmonised common subset could be scored",
         "Possible subset: name, email, phone, address, national ID, card number",
         "Other types reported separately, such as NRIC or FIN where supported"],
        ["E R2","K R2","AF R2","AH R2","AN R2","AX R2","BL R2"]),
 outputs=(["Decision where exposed: blocked, masked or allowed (E, K, AF)",
           "Findings with type and span where exposed (AH, AN, AX, AF)",
           "Score: AH 0 to 1; AN five levels; AF 0.0 or 1.0",
           "Masked text or change list (AI, AP, AX, BL)",
           "Latency; error"],
          ["K R5","AF R5","AH R5","AI R5","AN R5","AP R5","AX R5","BL R5"]),
 metrics=(["Detection rate (recall) per entity type; precision where spans are returned",
           "False-positive and false-negative rates, same breakdown",
           "Masking correctness: masked text equals expected, no residual PII",
           "Threshold sweeps only for score or likelihood outputs (AH, AN)",
           "Latency per call",
           "E and K expose no score; AF score looks like a flag"],
          ["AH R5","AN R5","AF R4","E R5","K R5","AP R5"]),
 arch=(["Suggested harness: loader, adapters, common result format, recorder, evaluator",
        "AH, AI: pip install plus spaCy model, or GHCR image",
        "E: Bedrock sensitive-information policy; AF: Sentinel beta key, Singapore IP",
        "AN, AP, AX: Google Cloud project; AX adds a Model Armor template",
        "BL: approved Cloak account for Web UI or API",
        "K: NeMo config with one backend; eval run could drive K only"],
       ["AH R7","AI R7","AN R7","AP R7","AX R7","BL R7","K R7","3e (d) access paths","3f (d) integration paths","3g (d) integration and access paths","3h (b) integration paths","3l (b) access and integration paths","3c Tools"]),
 diffs=(["Entity lists differ: AWS types, Presidio recognizers, SDP infoTypes, Cloak groups",
         "Shared backends, not independent: K-AH, AF-E, AX-AN",
         "AH, AN return findings only; AI masks only supplied spans",
         "AX basic mode uses a short, US-leaning fixed list",
         "BL needs approved access; Terms clause 3.4.7 benchmarking question open",
         "Google AUP testing clause not recorded in AN, AP or AX columns",
         "AF returns raw matches; Sentinel is closed beta; E has summary-level research",
         "BI regex scanner covers four PII shapes: see C3",
         "Output side is C2"],
        ["E R4","K R4","AF R4","AH R5","AI R3","AX R2","AX R8","BL R8","AN R8","3g (d) integration and access paths","3l (e) limits and terms"]),
)

G["C2"] = dict(
 name="Output-level PII and sensitive-data detection and masking in text",
 funcs=["E","L","AF","AH","AI","AN","AP","AY","BL"],
 inputs=(["Suggested: model responses, scripted or generated, with synthetic labelled PII",
          "Add clean responses, borderline strings and responses repeating prompt PII",
          "No product ships labelled response data; seed data would be built"],
         ["L R7","E R6","AF R7","AH R3","AY R7","3c Reuse"]),
 truth=(["Suggested: per response, PII type and span of each item",
         "Expected action (block, mask or allow) and final user-visible text",
         "Score the harmonised common entity subset, as in C1",
         "Other types reported separately"],
        ["L R5","E R2","AF R3","AY R2"]),
 outputs=(["Decision where exposed: blocked, masked or allowed (E, L, AF)",
           "Findings with type, span, score or likelihood (AH, AN, AY, AF)",
           "Final text or de-identified copy (AI, AP, AY, BL)",
           "Latency; error"],
          ["L R5","AF R5","AH R5","AI R5","AN R5","AP R5","AY R5","BL R5"]),
 metrics=(["Detection rate, false-positive and false-negative rates per entity type",
           "Masking correctness on the final text",
           "Threshold sweeps only for score or likelihood outputs (AH, AN)",
           "Latency per call; non-streaming runs first"],
          ["AH R5","AN R5","E R5","L R5","L R8"]),
 arch=(["Suggested harness feeding scripted or real main LLM responses",
        "Adapters, result format, recorder, evaluator as in C1",
        "L: NeMo output rail with one backend and its service",
        "AY: Model Armor response method, regional template, SDP basic or advanced",
        "nemoguardrails eval run could drive L only, on LLMRails"],
       ["L R7","AY R7","3h (b) integration paths","3e (d) access paths","3c Tools"]),
 diffs=(["Same entity-list, backend-sharing and access limits as C1",
         "L may release PII during streaming before the rewrite",
         "Rewrites under streaming need stream_first false",
         "AY basic list may not apply to responses; result shape unshown",
         "AF wraps AWS Bedrock Guardrails: backend shared with E, not independent",
         "NeMo evaluation tooling has no streaming: test non-streaming first",
         "Input side is C1"],
        ["L R4","L R8","AY R2","AY R3","AF R4","3c Engine coverage"]),
)

G["C3"] = dict(
 name="Input-level rule-based pattern matching in text (regex, word lists, fixed rules)",
 funcs=["E","N","AM","AO","BI","BK","BM"],
 inputs=(["Suggested: user messages that match and do not match the same rules",
          "Authored regex and word lists loaded into each product's own format",
          "BI, BK: strings built around their fixed documented rules",
          "No product dataset; strings would be written for the test"],
         ["N R7","AM R7","AO R7","BI R7","BK R7","BM R7","E R6"]),
 truth=(["Suggested: per string and rule set, expected match or no match",
         "Derived from the rule definitions, so the label is deterministic",
         "Expected spans where the product returns them",
         "BI, BK: expected outcome follows their fixed documented rules"],
        ["N R2","AM R2","AO R2","BI R2","BK R2","BM R2","E R4"]),
 outputs=(["Block or mask decision (E, N, BI, BK)",
           "Matched pattern or span, with score or likelihood (N, AM, AO, BI)",
           "Transformed text per match (BM, E); decoded hidden text (BK)",
           "Latency; error"],
          ["N R5","AM R5","AO R5","BI R5","BK R5","BM R5","E R5"]),
 metrics=(["Exact agreement with the expected match outcome per string",
           "False-positive and false-negative rates against the rules",
           "Span overlap where spans are returned (AM, AO)",
           "Latency, including slow-pattern cases",
           "No score curves: AM and AO scores are author-set"],
          ["N R5","AM R5","AO R5","BI R5","BM R4"]),
 arch=(["Suggested harness: rule loader, adapters, result format, recorder, evaluator",
        "N: NeMo config with input patterns and a stub LLM",
        "AM: local Analyzer with spaCy model; BI, BK: llamafirewall, no key",
        "AO: Google Cloud project, DLP User role; E: Bedrock policy",
        "BM: approved Cloak account; custom entities set per project"],
       ["N R7","AM R7","AO R7","BI R7","BK R7","BM R7","E R7","3c Tools"]),
 diffs=(["Authored patterns for N, AM, AO, BM, E; BI, BK rules fixed",
         "BI, BK rules could be re-expressed as regex for the other products",
         "Regex dialects, limits and matching methods differ; AO caps regex at 1000",
         "AM and AO add context or hotword rules; the others do not",
         "BM LLM entity is Beta and not pattern matching: test apart",
         "BM Terms clause 3.4.7 benchmarking question is an open item",
         "Output side is C4; the N retrieval variant is C17"],
        ["AO R6","BI R6","BK R2","BM R4","BM R8","N R3","N R8","AM R4"]),
)

G["C4"] = dict(
 name="Output-level rule-based pattern matching in text (regex, word lists, fixed rules)",
 funcs=["E","N","AM","AO","BI","BK","BM"],
 inputs=(["Suggested: bot responses scripted by a stub LLM",
          "Responses that match and do not match each rule",
          "Same rule lists as C3; no product dataset"],
         ["N R7","AM R3","AO R3","BI R3","BK R3","3c Reuse"]),
 truth=(["Suggested: per response and rule set, expected match or no match",
         "Derived from the rule definitions, so deterministic",
         "Expected final text where a product transforms matches"],
        ["N R2","AM R2","AO R2","BK R2","BM R5","E R5"]),
 outputs=(["Block or mask decision (E, N, BI, BK)",
           "Matched pattern or span, with score or likelihood (N, AM, AO, BI)",
           "Transformed text per match (BM, E)",
           "Latency; error"],
          ["N R5","AM R5","AO R5","BI R5","BK R5","BM R5"]),
 metrics=(["Exact agreement with the expected match outcome per response",
           "False-positive and false-negative rates against the rules",
           "Span overlap where spans are returned (AM, AO)",
           "Latency"],
          ["N R5","AM R5","AO R5","BI R5"]),
 arch=(["Suggested harness with a stub LLM returning scripted text",
        "N: NeMo config with output patterns, both engines",
        "Other adapters as in C3: AM, AO, BI, BK, BM, E",
        "nemoguardrails eval run could drive N on LLMRails"],
       ["N R7","3b surface table","3c Tools","E R7"]),
 diffs=(["Same limits as C3: authored patterns, BI and BK fixed, dialects differ",
         "N has a separate output check; the others take any string",
         "N output check has no exception path",
         "BI and BK are outside the default role map",
         "Input side is C3"],
        ["N R3","N R8","BI R3","BK R3","AM R3","AO R3"]),
)

G["C5"] = dict(
 name="Reversible tokenisation of text before the model (encrypt side)",
 funcs=["AJ","AQ","BN"],
 inputs=(["Suggested: user messages with synthetic labelled entities to tokenise",
          "Repeated values, so token consistency can be observed",
          "Same entity set across the three products",
          "No product dataset; strings would be written for the test"],
         ["AJ R7","AQ R7","BN R7"]),
 truth=(["Suggested: per entity, original value and span in the outgoing text",
         "Expected: no original value survives in the tokenised text",
         "Expected token properties per product: format, length, alphabet"],
        ["AJ R4","AQ R4","BN R4"]),
 outputs=(["Tokenised text with item list (AJ) or change summary (AQ)",
           "Ciphertext strings in the text (BN)",
           "Token format, length and alphabet",
           "Latency; error"],
          ["AJ R5","AQ R5","BN R5"]),
 metrics=(["Residual-PII rate: original values left in the tokenised text",
           "Token format conformity: length, alphabet, base64",
           "Token consistency for repeated values, observed per product",
           "Latency per call; round-trip exactness is scored in C6"],
          ["AJ R4","AQ R4","BN R2"]),
 arch=(["Suggested harness: loader, adapters, key setup, recorder, evaluator",
        "AJ: Anonymizer with a caller-held AES key; local, no account",
        "AQ: Google Cloud project, DLP and KMS APIs, wrapped key in region",
        "BN: approved Cloak account and a Secrets Manager secret"],
       ["AJ R7","AQ R7","BN R7","3f (d) integration paths","3g (d) integration and access paths","3l (b) access and integration paths"]),
 diffs=(["Keys differ: caller-held (AJ), Cloud KMS wrapped (AQ), Secrets Manager (BN)",
         "AJ uses a random vector per entity; AQ repeats tokens per key",
         "AQ docs disagree on whether AES-SIV keeps length",
         "BN needs approved access; Terms clause 3.4.7 benchmarking question open",
         "Entity detection differs: AJ uses the Analyzer, AQ and BN their own",
         "Restore side is C6"],
        ["AJ R4","AQ R4","BN R8","AJ R3","AQ R2","3l (e) limits and terms"]),
)

G["C6"] = dict(
 name="Restoring tokens in model output (decrypt side)",
 funcs=["AJ","AQ","BN"],
 inputs=(["Suggested: mock model replies that echo, edit, drop or reorder tokens",
          "Replies with several tokens, and replies with none",
          "Wrong key or secret, and damaged-token cases",
          "Tokens produced by C5 runs"],
         ["AJ R7","AQ R7","BN R7","AJ R3"]),
 truth=(["Suggested: per reply, expected restored text with original values",
         "Echoed tokens restore exactly; dropped tokens stay absent",
         "Wrong-key and damaged-token expectations are open: observe and record"],
        ["AJ R1","AQ R1","BN R1","AJ R8","AQ R8"]),
 outputs=(["Restored text and item list (AJ)",
           "Re-identified item and change summary (AQ)",
           "Decrypted value per pasted token (BN Web UI)",
           "Error or silent wrong text; latency"],
          ["AJ R5","AQ R5","BN R5","BN R8"]),
 metrics=(["Restore exactness per token",
           "Partial-restore rate for edited or reordered tokens",
           "Failure handling: clear error versus silently wrong text",
           "Latency per call"],
          ["AJ R7","AQ R7","BN R7"]),
 arch=(["Suggested harness replaying mock replies, with key handling",
        "AJ: Deanonymize with the same key, token spans and types",
        "AQ: re-identify with the same wrapped key and surrogate name",
        "BN: Web UI decrypts one pasted token; API takes rows"],
       ["AJ R6","AQ R6","BN R6","3f (d) integration paths","3g (d) integration and access paths"]),
 diffs=(["AJ needs token offsets; model edits can move them",
         "BN restores one value at a time in the UI",
         "AQ re-identify may not accept conversation or batch items",
         "BN Terms clause 3.4.7 benchmarking question is an open item",
         "Long encrypted tokens may be altered by a real model",
         "Encrypt side is C5"],
        ["AJ R3","AJ R8","BN R3","BN R8","AQ R8"]),
)

G["C7"] = dict(
 name="PII and sensitive-text detection and redaction in images",
 funcs=["AK","AR","BC"],
 inputs=(["Suggested: images of known text carrying labelled synthetic PII, plus clean images",
          "Screenshots, scans and photos; varied fonts, sizes and layouts",
          "AR also: images with ID-type objects for its object detectors",
          "Preview features (AR faces, BC) with synthetic data only"],
         ["AK R7","AR R7","BC R7","AR R2","3h (d) locations and feature availability"]),
 truth=(["Suggested: per image, PII text items with entity type and box",
         "Expected redacted regions; clean images expect none",
         "Hand-drawn box coordinates; box origin conventions differ",
         "Entity lists differ: score a harmonised subset"],
        ["AK R2","AR R2","BC R2","AR R8","BC R8"]),
 outputs=(["Redacted image (AK, AR, BC)",
           "Findings with type, score or likelihood and box",
           "Extracted text (BC)",
           "Latency; error"],
          ["AK R5","AR R5","BC R5"]),
 metrics=(["Per-entity detection rate on text read from the image",
           "Box overlap with hand-drawn ground truth",
           "Residual readable PII after redaction, checked by re-running OCR",
           "False-positive rate on clean images; latency"],
          ["AK R5","AR R5","BC R5"]),
 arch=(["Suggested harness: image loader, adapters, box scorer, recorder, evaluator",
        "AK: Image Redactor with Tesseract and spaCy model, or Docker image",
        "AR: Google Cloud project, DLP API, regional endpoint such as Singapore",
        "BC: Model Armor template in us or eu with image modality",
        "BC also needs an advanced SDP template; redaction a de-identify template"],
       ["AK R7","AR R7","BC R7","3f (d) integration paths","3g (f) region and availability","3h (d) locations and feature availability"]),
 diffs=(["AK is beta; BC is Preview, us and eu only",
         "AR adds object detectors beyond text",
         "BC wraps SDP image handling: backend shared with AR, not independent",
         "OCR engines differ; AK thresholds differ between Python and REST",
         "Format and size limits are stated for AR and BC only",
         "No direction flag: one group kept; BC response-side images not shown",
         "Google AUP testing clause is recorded for BC as an open item"],
        ["AK R4","AK R5","AR R6","BC R3","BC R4","BC R8","AK R3"]),
)

G["C8"] = dict(
 name="Harmful-content classification of input (user prompts)",
 funcs=["G","V","AA","AG","AT","BD"],
 inputs=(["Suggested: single-turn user prompts, harmful and benign, plus benign near-misses",
          "NeMo seeds: Anthropic red-team-attempts and helpful-base prompts, binary label only",
          "Litmus Undesirable Content themes could guide cases; it publishes no prompts",
          "Multilingual cases: Singlish, Chinese, Malay, Tamil (AA, BD); AT nine languages"],
         ["G R7","V R7","AA R7","AG R7","AT R7","BD R2","3c Datasets","3n Reuse"]),
 truth=(["Suggested: per prompt, binary harmful or benign label",
         "Plus category label mapped to a common taxonomy",
         "Taxonomies differ: G Nemotron codes; V S1 to S14; AA, BD six",
         "AG five categories; AT four plus CSAM",
         "Compare per category only where a mapping exists"],
        ["G R2","V R2","AA R2","AG R2","AT R2","BD R2"]),
 outputs=(["Decision where exposed (G, V, AG, AT overall match state)",
           "Category codes, per-category scores or probabilities (AA, BD, AT)",
           "First-token probability for V only if extracted",
           "Latency; error"],
          ["G R5","V R5","AA R5","AG R5","AT R5","BD R5"]),
 metrics=(["True-positive, false-positive, false-negative rates on binary harmful label",
           "Measured at each product's own decision point",
           "AUPRC and sweeps only where probabilities exist: AA, BD, V if extracted",
           "AG shows 0.0 or 1.0; AT gives match states and levels",
           "BD ships no cut-off; AA scores have no server threshold"],
          ["3c Published results","AG R5","AT R5","BD R5","AA R5"]),
 arch=(["Suggested harness: loader, adapters, common result format, recorder, evaluator",
        "G: NeMo input rail, safety model endpoint, prompt",
        "V: GPU-served Llama Guard with template and verdict parser",
        "AA, AG: Sentinel beta key, Singapore IP; BD: local Transformers",
        "AT: Google Cloud project, Model Armor template, regional endpoint"],
       ["G R6","3d (c) integration paths","3e (d) access paths","3i (c) dependencies and access","3h (b) integration paths","3c Tools"]),
 diffs=(["AA and BD share LionGuard models: not independent",
         "G can call Llama Guard: G and V may share a model",
         "AG wraps AWS Bedrock Guardrails and has no self-harm category",
         "AT model undisclosed; default confidence unclear; Google AUP clause open item",
         "BD embedder terms (OpenAI, Gemini, Gemma) are open items",
         "Taxonomies and thresholds differ; Sentinel is closed beta"],
        ["AG R2","AA R2","G R5","V R5","AT R4","AT R8","BD R8","3i (c) dependencies and access","3e (b) catalogue"]),
)
