import json, re
SP = "/home/user/guardrail_research/benchtest/scratchpad/merger/sdp/"
ROOT = "/home/user/guardrail_research/benchtest/drafts/"
P = json.load(open(SP + "pieces.json"))
RN = open(SP + "inventory_reviewer_notes.md", encoding="utf-8").read()
gs = P["gs"]


def g(prefix):
    return sum(v[1] for k, v in gs.items() if k.startswith(prefix))


t = []
A = t.append
A("# Sensitive Data Protection merge: change log")
A("")
A("Date: 2026-10-09. Phase: P6 (merge). Product: sdp (prefix `Sensitive Data Protection:`, columns SD1 to SD6).")
A("")
A("Inputs merged: sdp_brief.md, sdp_cols_a.md (SD1 to SD3), sdp_cols_b.md (SD4 to SD6), sdp_inventory.md, sdp_triage.md (98 items), sdp_resolutions_1.md (26 items, T1 to T49), sdp_resolutions_2.md (32 items, T50 to T98), and main's rulings on the resolver questions (`scratchpad/main/queue.md`, rows 'sdp P5 r1' and 'sdp P5 r2'). Rulings applied: R002, R007, R009, R011, R012, R013, R014, R015, R018 (CP1), R019, R020. Outputs: sdp_two_level.md, sdp_inventory_final.md, sdp_changes.md, sdp_summaries_preview.md. No eval-tooling sheet (SDP has none). Merge scripts and the machine-readable edit log are in `benchtest/scratchpad/merger/sdp/` (merge_sdp.py, cols_edits.py, inv_edits.py, log.json); every edit below was applied by exact-match replacement and asserted to match once.")
A("")
A("Format of the entries: location | before (shortened; Summaries in full with word counts) | after | reason (T-id, hygiene or style). 'Hygiene' = label or wording rules of drafts/README.md sections 3 and 4 that the triage listed under 'Label hygiene'. 'Style' = the triage's 'Style issues' list. Lines are never wrapped; `\\|` marks a literal pipe in a quotation.")
A("")
A("## 0. Counts")
A("")
A(f"- Individually logged edits: {P['n_cols']} in the columns (SD1 to SD6), {P['n_inv']} in the inventory, plus {P['n_gsub']} global pattern replacements (section 1) that changed {sum(v[1] for v in gs.values())} lines or spans. Total log entries: {P['n_cols'] + P['n_inv'] + P['n_gsub']}.")
A("- Summaries changed: 14 (SD1 R4, SD1 R6, SD2 R5, SD2 R6, SD2 R8, SD3 R1, SD3 R4, SD4 R4, SD4 R5, SD5 R1, SD5 R2, SD6 R2, SD6 R4, SD6 R5). The other 40 Summaries are unchanged from the drafts (the 54 counted include R8 and R9 Summaries).")
import collections
_L = json.load(open(SP + "log.json"))
_changed = sorted({int(x[1:]) for e in _L for x in re.findall(r"T\d+", e["tid"])})
_verd = {}
for _fn in ["sdp_resolutions_1.md", "sdp_resolutions_2.md"]:
    _txt = open(ROOT + _fn, encoding="utf-8").read()
    for _ln in _txt[_txt.rfind("## Summary table"):].split("\n"):
        _m = re.match(r"^\| (T\d+) \| ([^|]+) \|", _ln)
        if _m:
            _verd[int(_m.group(1)[1:])] = _m.group(2).strip()
_closed_nochange = sorted(t for t, v in _verd.items() if (v.startswith("RESOLVED") or v.startswith("CORRECTION")) and t not in _changed)
_open_changed = sorted(t for t in _changed if t in _verd and not (_verd[t].startswith("RESOLVED") or _verd[t].startswith("CORRECTION")))
A(f"- Items from the triage: 98. Draft text changed for {len(_changed)} T-ids (" + ", ".join(f"T{x}" for x in _changed) + "), plus the hygiene and style items that carry no T-id of their own. Of these, " + ", ".join(f"T{x}" for x in _open_changed) + " are PARTLY RESOLVED or STILL OPEN after P5 (the change records what was found; the open part stays in R8 or as a labelled bullet). Resolved with no text change: " + ", ".join(f"T{x}" for x in _closed_nochange) + ". Left open for the bench: " + str(P["n_open"]) + " items in total (section 5).")
A("- Final inventory row counts for the `build_sdp_inventory.py` config (P8): (a) 15, (b) 24, (c) 12, (d) 13, (e) 16, (f) 7 = 87. No resolution changed a count (T79 kept block (d) at 13, T24 added no row). Column tables: (a) 8 cells, (b) 7, (c) 8, (d) 8, (e) 4, (f) 4. Markers needed in the config `markers` tuple: `— (inventory only, not in Table 3)` (R011); no legacy or planned marker is used.")
A("- Columns: 6 (SD1 to SD6), exact headers as in sdp_brief.md; no column SD7 (content policy is inventory only, R018).")
A("")
A("## 1. Global changes (apply to every column or to the inventory)")
A("")
A("| Scope | Before | After | Reason |")
A("|---|---|---|---|")
A("| Files | sdp_cols_a.md (SD1 to SD3) and sdp_cols_b.md (SD4 to SD6), sdp_inventory.md with `## Reviewer notes` | sdp_two_level.md (SD1 to SD6 in order), sdp_inventory_final.md without Reviewer notes | merge; the inventory Reviewer notes are kept in section 6; the column drafts had none (T96) |")
A("| All columns: code citations | A: `packages/google-cloud-dlp/...@tag:line` (" + str(g("T97|packages")) + " cites); B: `dlp_v2/...@tag:line` (" + str(g("T97|(?<![/\\w])dlp_v2")) + " cites) and `dlp/gapic_version.py@tag:16` (" + str(g("T97|(?<![/\\w])dlp/gapic")) + " cites) | one package-relative form with the `google/cloud/` prefix, then `@google-cloud-dlp-v3.40.0:<line>`; the R9 blob URLs keep the full repo path | T97: README section 3 rule 7; 61 line numbers were verified at the tag by the resolver |")
A(f"| All columns: pointers to other columns | 'the detection column' ({g('style 4|the detection')}), 'the reversible-tokenisation column' ({g('style 4|the reversible')}), 'the image columns' ({g('style 4|they are covered')}), 'the SD1 and SD2 columns' ({g('style 4|the SD1')}), 'the SD5 column' ({g('style 4|the SD5')} plus 1 in SD6 R8), 'the SD3 column' and 'the SD6 column' (1 each in specific bullets), 'SD1' (1) | header words, e.g. 'the sensitive-data detection in text column', 'the masking and de-identification in text column', 'the image detection and redaction column' | style 4: column ids are not visible on the sheet |")
A("| All columns: out-of-purpose statement (no prompt-injection, jailbreak, toxicity or topic-drift detection) | [Inferred] in SD1 to SD3 R2; [Not disclosed] in SD4 to SD6 R2 | one pattern in all six: a [Documented] purpose sentence (SD1 R2) plus an `Out of purpose:` bullet labelled [Inferred] with its premise named | T19 under R015 (the brief's [Documented] suggestion conflicts with README section 3 rule 2) |")
A("| All columns: absence claims | [Documented] or [Inferred] on 'no evaluation method', 'no SLA row', 'no apply method' | [Not disclosed] with the pages checked (R020); positive documented definitions beside them keep [Documented] | T9, T22, T51, T54, T44, T91 |")
A("| All columns: [Inferred] bullets without a premise | 48 of 48 in B, 10 of 43 in A did not name a premise | 24 bullets gained a `(premise: ...)` clause; R7 test-design bullets are [Inferred] by the R7 rule and were left as written | T98 |")
A("| SD1 to SD3 R7 | first Detail bullet started `Minimum setup:` without the bold markers | `**Minimum setup:**` (B already did) | style 8 / README section 4 |")
A("| SD1, SD3, SD4, SD5, SD6 R8 and R9 | customer-data terms 'not read'; no terms URLs | R8 bullet states what the Google Cloud terms pages say (R019) and the pages checked; 4 terms URLs in R9 of each of the five columns (SD6 also the Acceptable Use Policy) | T92, T93 (main accepted the resolver's text: general terms [Documented] plus [Inferred] applicability; benchmarking and AUP in SD6 R7 and R8 and INV(f)) |")
A("| R9 of all columns | 6 lists | 37 URL bullets added in total (SD1 5, SD2 4, SD3 5, SD4 13, SD5 4, SD6 6): pages cited in new bullets (REST Regex, response pages, deidentifyTemplates, InspectResult, audit-logging, Cloud Logging and Cloud KMS pages) and the terms pages named in R8 | README section 4: every URL cited must be listed; R9 completeness |")
A("| Cross-product headers in Detail | 'provisional header' remarks; Output-level Model Armor header unwritten | both Model Armor sensitive-data headers written in full; Presidio and Sentinel headers unchanged and 'provisional' dropped. Compared on 2026-10-09 with modelarmor_cols_a/b.md (MA5, MA6, MA10), presidio_cols_a/b.md (PD1, PD2) and sentinel_two_level.md (SN6): all match. modelarmor_two_level.md and presidio_two_level.md do not exist yet, so main should re-compare when those merge | T6 (frozen by R016 and R017) |")
A("| Rulings cited inside cells | 'ruling R012 keeps those internals out of this column' (resolver text) | 'those internals are not repeated here' | style: ruling ids are process references and mean nothing to a sheet reader (deviation from the resolver's exact text, same meaning) |")
A("| Inventory: process and first-person wording | 'my count' (25 cells), 'my own', 'this sheet', 'not exercised, read-only rule', 'Not covered in this sheet', 'Counts that are mine', 'provisional' | 'count of ...', 'the rule in the block note', 'Covered by the Model Armor columns, not repeated here', neutral wording | T89, T90 |")
A("| Inventory: Reviewer notes | `## Reviewer notes` section with a self-check | removed from the final; moved to section 6 | README section 7 item 5 |")
A("| Inventory (d): Google sample repositories | not read | S3 and JDBC guide targets read; cited with `[Documented: repo GoogleCloudPlatform/...@sha]` and the plain-text hint 'Google sample repository, supporting only' | T79, main ruling (R013: Google sample repos are supporting only) |")
A("")
A("## 2. Column and row changes")
A("")
A("Entries are in the order applied. 'Detail split' = one bullet became several; Summaries are quoted in full with word counts (excluding the trailing label).")
A("")
A(P["sec2"])
A("### Global pattern replacements (counts)")
A("")
A("| Pattern | Replacement | Spans changed | T / style |")
A("|---|---|---|---|")
for k, (reason, n) in gs.items():
    tid = k.split("|")[0]
    pat = k.split("|", 1)[1]
    A(f"| `{pat.replace('|', chr(92) + '|')}` | see reason | {n} | {tid}: {reason.split(' (')[0]} |")
A("")
A("## 3. Inventory changes (sdp_inventory.md to sdp_inventory_final.md)")
A("")
A("Block row counts are unchanged: (a) 15, (b) 24, (c) 12, (d) 13, (e) 16, (f) 7. Cell edits that repeat across rows (T88, T89) are grouped.")
A("")
A(P["sec3"])
A("")
A("## 4. Conflict decisions")
A("")
A("Rule applied throughout (README section 3 rule 4, R007 item 4): two official statements that disagree are kept as two bullets or two cell facts, each with its own label, plus a note naming the conflict; none is picked silently. Code at the pinned tag is preferred over docs only for API-surface questions (brief).")
A("")
A("| # | Conflict | Side 1 (label) | Side 2 (label) | Decision |")
A("|---|---|---|---|---|")
A("| 1 | Image formats for inspection and redaction (brief C1; contradiction 2) | REST image.redact: 'PNG, JPEG, SVG or BMP'; inspect guide: 'JPEG, BMP, PNG, and SVG' [Documented] | redaction guide: 'JPEG, BMP, and PNG' and 'not supported for SVG, PDF, XLSX, PPTX, or DOCX'; file-types table: 'bmp, gif, jpe, jpeg, jpg, png'; method-types: 'JPEG, PNG, or TIFF' [Documented]; client enum without GIF [Documented: repo] | No pick. SD5 R6 carries all six statements; INV(a) image row now carries all six (it had three) plus the docstring as a labelled fact; the disagreement itself is [Inferred]. Test stays open (T67, R8). |")
A("| 2 | Content policy 'synchronous verdict' versus API surface (brief C2; contradiction 1) | overview promises 'immediate, synchronous verdicts'; IAM defines `dlp.contentPolicies.apply` and the role DLP Content Policies Consumer [Documented] | REST resource, RPC reference, discovery document revision 20261006 and client v3.40.0 list create, delete, get, list and patch only [Documented; Documented: repo] | The R018 upgrade condition (a documented direct apply or evaluate method) is not met: the absence is [Not disclosed] naming the pages. SD7 stays inventory only with the R011 marker; no column and nothing returns to the user. The apply permission is [Documented]; its use by the Gemini Enterprise service account is [Inferred]. |")
A("| 3 | CryptoHashConfig output (contradiction 5) | table: '32-byte hexadecimal string' [Documented] | body text and pseudonymization page: base64 [Documented] | Two bullets kept (SD3 R4, INV(c) hash row). 'HMAC-SHA-256' confirmed on the transformation reference and pseudonymization pages. Test open (T56). |")
A("| 4 | AES-SIV token length (contradiction 4) | table row: 'of the same length' [Documented] | deterministic section and pseudonymization page: length not preserved [Documented] | Three bullets kept in SD4 R4; the SD4 R4 Summary no longer says 'of any length' and states the disagreement; the conflict is now also in the INV(c) AES-SIV row. Test open (T15). |")
A("| 5 | Bucketing, date shift, time part: free text or tables (contradiction 6) | table 'Any' and 'Dates/Times'; discovery schema accepts them inside an infoType transformation [Documented] | bucketing text says numerical data; samples use records; `dateShiftConfig.cryptoKey` 'Can only be applied to table items' [Documented] | SD3 R1 and R4 Summaries narrowed to 'shown only on table fields'; free-text use stays [To be verified] in one bullet (split from the sample fact). Test open (T13). |")
A("| 6 | Default infoTypes when none are listed (contradiction 7; brief O1) | concepts page: a testing-only default list; de-identify page: 'default set (ALL_BASIC)'; de-identification: 'all built-in infoTypes that don't have a transformation' [Documented] | InspectConfig and the three REST method pages: 'may automatically choose ... may be all types'; image guides: 'the most common infoTypes' and 'Default infoTypes don't include objects in images' [Documented] | All five wordings quoted, no label upgrade; ALL_BASIC membership is [Not disclosed] (no page defines it). Membership test open (T43). |")
A("| 7 | Rule order (contradiction 8; T49) | guide and its worked example: rules applied in the order written; release note 2026-02-23: 'Enhanced rule ordering' at general availability [Documented] | REST InspectConfig.ruleSet: 'Exclusion rules ... are executed in the end' (page footer 2026-09-05) [Documented] | Both kept as separate [Documented] bullets plus the worked example. The draft's inference 'the REST text may be older' is weakened to '[Inferred] ... may be unchanged text rather than older text (premise: footer dates)'. Test open (T50). |")
A("| 8 | Dictionary size (contradiction 8; T48) | 'up to several tens of thousands' (concepts) [Documented] | 'at most several hundred thousand' (custom overview); 128 KB inline and 512 KB from Cloud Storage (limits) [Documented] | Kept as two labelled bullets; units not reconciled; test open. |")
A("| 9 | Bounding-box origin (contradiction 3; T68) | REST InspectResult and client: '(0,0) is upper left' [Documented; Documented: repo] | inspect guide: '(0,0) at the bottom left'; concepts page: 'bottom-left corner' [Documented] | Four statements kept in SD5 R5; re-read raw by the resolver, no page decides it. Test open (T68). |")
A("| 10 | 3,000-finding limit: cap or not | limits page: 'Maximum number of findings per request \\| 3,000' [Documented] | REST InspectConfig: 'the value that you set or 3,000, whichever is lower. This value isn't a hard limit.' [Documented] | Two bullets in SD1 R6; INV(e) findings row carries both; SD1 R6 Summary no longer says 'capped at ... 3,000 findings'. De-identification returns the stated error message above 3,000 (SD3 R5 unchanged). T20. |")
A("| 11 | Limits and content.reidentify (contradiction 10; T21) | INV(e) applied 0.5 MB and 100 transformations to reidentify as [Documented] | limits table is headed 'inspecting and de-identifying content' and never names reidentify [Documented] | INV(e) rows aligned with SD4 R6: the table fact is [Documented]; application to reidentify is [Inferred]; 'Applies to' narrowed. |")
A("| 12 | SLA coverage of reidentify and redact (contradiction 11; T22) | columns [Inferred] | INV(e) [Not disclosed] | One pattern: 'Covered Service' definition [Documented]; no objective for reidentify or image.redact [Not disclosed] naming the SLA page (R020). |")
A("| 13 | Document-category infoTypes on text (contradiction 9; T41) | SD6 R2 stated as [Documented] that they 'classify text, not pixels' | SD1 R2 and R8: unknown whether they run on a plain string or in asia-southeast1 | SD6 R2 split: names and descriptions [Documented]; 'text-side analogues' is [Inferred] with the open question pointed out. Test open (T41). |")
A("| 14 | Hash row coverage (contradiction 13; T65) | brief and INV(c): SD3 and SD4 headers | SD4 R1: hashing is the one-way contrast, row belongs with masking | Main's ruling: hashing is one-way, SD4 is reversible tokenisation (R018 keeps SD4). INV(c) hash row covered by the SD3 header only; SD4 stays on the FPE and AES-SIV rows (2 rows). |")
A("| 15 | Out-of-purpose label (contradiction 12; T19) | brief: [Documented]; SD4 to SD6: [Not disclosed] | SD1 to SD3: [Inferred] | R015: [Inferred] with the premise named, in all six columns. |")
A("| 16 | Python version (contradiction 15; T84) | libraries page: samples compatible with 'Python 2.7.x and 3.4 and higher' [Documented] | package at the tag: `python_requires=\">=3.10\"` [Documented: repo] | No change: two bullets kept (SD1 R7, INV(d)); the samples text is a docs-staleness note. |")
A("| 17 | Region lists (contradiction 16; T83) | locations page: 43 regions including asia-southeast3 [Documented] | REST reference: 42, without asia-southeast3 [Documented] | Two labelled facts kept; counts [Inferred]; the release note of 2026-01-20 added to INV(f) (optional item). |")
A("| 18 | Two rate-quota rows with one name (contradiction 17) | 600 per minute per region (global endpoint with a location) [Documented] | 100 per minute per region (regional endpoint) [Documented] | Kept; distinguished by description as the limits page does. |")
A("| 19 | Domain and seeds (contradiction 18; T85) | seeds.md carried the old host | docs now on docs.cloud.google.com | Resolved: seeds.md already updated; HTTP 301 facts observed 2026-10-09 are in INV and need no change. |")
A("| 20 | Date-sensitive release notes (T44; main: keep both statements) | PERSON_NAME new version promoted to stable 'In 30 days' from 2026-10-03 [Documented]; about 2026-11-02 [Inferred] | MEDICAL_ID legacy window 90 days from 2026-07-13, ending about 2026-10-11 [Inferred] | Both dated statements kept with their [Inferred] premise. Re-read the release notes at P7 and P9: a promotion note or a MEDICAL_ID change after 2026-10-09 would change SD1 R4, R7 and INV(b) Health. |")
A("| 21 | MEDICAL_ID behaviour (T44 CORRECTION) | draft: change applies to version `latest`, old behaviour on `stable` | release note 2026-07-13: unset or stable get the change; `legacy` keeps the old behaviour for 90 days | Draft was wrong; INV(b) Health row corrected. |")
A("| 22 | Sample repositories as sources (main ruling) | R013: vendor repos are read; Google sample repos are supporting | S3 and JDBC guide targets are Google sample or community repos | Cited as supporting only, with the pin and the plain-text hint; no product behaviour rests on them (INV(d) only). |")
A("")
A("## 5. Remaining open items")
A("")
A(f"Counts after P5: {P['n_closed']} items closed by a resolution or ruling; {P['n_open']} stay open ({', '.join(f'{k} {v}' for k, v in sorted(P['by_class'].items()))}). Class b items (41, honest gaps and tests) stay in R8 or as [To be verified] / [Not disclosed] bullets, per the rule. 'Not handled' means the resolver left a class b item for the bench because no document can settle it. Triage locations are quoted as they stood in the drafts (line references are not carried over).")
A("")
A(P["stay"])
A("")
A("Items for the bench or the verifier worth naming (all unchanged by this merge):")
A("- Re-read due: release notes (T44), infoType reference counts (T46: 261, 240 and 21, 51, 43 regions), limits page values (T20), and quote sweep at P7. Pricing and SLA pages are on cloud.google.com, the rest on docs.cloud.google.com.")
A("- T8 (Google Cloud blog and Context7 not used): default stands, no draft depends on it.")
A("- T9 and T10 (content policy): the user question is not reopened (no documented apply or evaluate method). To test SD7 the bench needs a Gemini Enterprise tenant on a non-Business edition (T95).")
A("- T36 (context-length limits): not carried into R8; only a byte limit is documented (low impact).")
A("")
A("## 6. Moved Reviewer notes")
A("")
A("sdp_cols_a.md and sdp_cols_b.md had no `## Reviewer notes` section (T96: the drafters' notes were lost with an earlier session; the resolver's quote sweep over 477 quoted fragments found 467 verbatim and 10 that are the draft's own words between quoted prices, two class paths in storage.py and three descriptive phrases, so no fact depends on a summarising fetch). The inventory notes below are kept verbatim from sdp_inventory.md; the status line after each group says what the merge did with it.")
A("")
A(RN.replace("## Reviewer notes", "### Inventory Reviewer notes (verbatim)", 1))
A("### Status of the inventory notes after the merge")
A("")
A("- Row counts: unchanged (15/24/12/13/16/7 = 87).")
A("- Covered-by decisions bullet 1: SD4 is now added only for the FPE and AES-SIV objects (T65); block (c) has the SD4 header on 2 rows. Bullet 2: the Model Armor, Gemini Enterprise, Data Fusion, BigQuery and Dataflow/S3/JDBC rows keep the R011 marker (T5: R011 plus R012). Bullets 3 and 4: the content policy is inventory only (R018); the headers are frozen at CP1 (prefix `Sensitive Data Protection:`, six columns).")
A("- Conflicts: image formats now six statements (T66); content policy: apply permission and role added, no method found (T9); hash output unchanged (T56 open); bucketing unchanged (T13 open); region list: release note added (T83); libraries page: unchanged (T84); limits page quota names: unchanged; domain: resolved (T85).")
A("- Counts made by the drafter: kept as [Inferred] with the counting rule; recounted by the resolver on 2026-10-09 (T46: 261; 240 and 21; 24 groups summing to 261; 43 regions).")
A("- 'Uncertain or not read' bullets: 1 (gcloud group) unchanged; 2 (demo app) now [Not disclosed] (T94); 3 (python-dlp archive notice) read and [Documented: repo googleapis/python-dlp@21b91b9d] (T81); 4 (Apigee, Data Fusion, BigQuery, S3, JDBC) read, row rewritten (T79); 5 (other libraries not read) sentence deleted (T80); 6 (Model Armor internals) unchanged; 7 (customer-data terms) read (T92); 8 (bucketing on free text) unchanged, open (T13); 9 (DOCUMENT_TYPE/CONTEXT regions) unchanged, open (T41).")
A("- 'Facts from summarising fetches: none': unchanged; supported by the resolver's quote sweep.")
A("")
A("## 7. Self-check")
A("")
A("### Mechanical checker (run from the repo root after the merge)")
A("")
A("```")
A("python benchtest/tools/check_drafts.py columns benchtest/drafts/sdp_two_level.md --final --expect 6")
A(P["c_res"])
A("python benchtest/tools/check_drafts.py inventory benchtest/drafts/sdp_inventory_final.md --headers benchtest/drafts/sdp_two_level.md")
for l in P["tables"]:
    A(l)
A(P["i_res"])
A("```")
A("")
A("The task's command form `drafts/<slug>_two_level.md` was run as `benchtest/drafts/...` from the repo root; same files.")
A("")
A("### Summary word counts (excluding the trailing bold label; limit 45, R7 60) and labels")
A("")
A(P["sc1"])
A("")
A("54 Summaries (6 columns x 9 rows): 0 over the limit; R1 to R7 (42) all end with one bold allowed label; R8 (6) start `**Key open questions.**` with no label; R9 (6) are plain. Largest: see the table (R7 Summaries up to 60).")
A("")
A("### Labels, bullets and R9 (R1 to R7 Detail bullets all end with a bold label; R8 and R9 bullets unlabelled)")
A("")
A(P["sc2"])
A("")
A("- Pinned refs: every `[Documented: repo googleapis/google-cloud-python@google-cloud-dlp-v3.40.0]` bullet has a matching blob URL with the tag in R9 of the same column (script check: 0 problems). Docs facts carry no pin (no public docs repo), only the read date, as the brief requires. No `[Documented: develop/unreleased]` anywhere.")
A("- R9: one URL per bullet, no duplicates within a column (script check). Every URL named in the new bullets is in R9. Not listed in R9: the Google API discovery document for the DLP API (on the dlp.googleapis.com API host, cited in plain text only; see QUESTIONS in the report).")
A("- Inventory: 87 rows, every row has the header's cell count, no `**`, backtick or literal pipe in a cell; every Covered-by cell is a list of exact headers or one marker; labels are the six allowed forms only (checker).")
A("- Summary entailment spot-check of the 14 changed Summaries against their row's Detail: each claim has a bullet (SD3 R1 gained one bullet for 'shown only on table fields', T12).")
A("")
A("### Known-wrong strings (lessons.md item 6): matches left in the finals")
A("")
A("| String | sdp_two_level.md | sdp_inventory_final.md | Why it was wrong or changed |")
A("|---|---|---|---|")
A(P["grep"])
A("")
A("## 8. Notes for main (P8 config and follow-up)")
A("")
A("- `build_sdp_inventory.py`: BLOCKS counts 15/24/12/13/16/7; `covered` header 'Covered by Table 3 column'; `markers` tuple = (`— (inventory only, not in Table 3)`,); sheet letter by registry order (not written in any table). Blocks (e) and (f) have no Covered-by column. The scope paragraph and the (b) note (a one-paragraph merged note above the table) contain URLs in short-name definitions (`docs/slug` is a placeholder, not a link).")
A("- Url-checker: harvest only R9 bullets and Source URL cells; skip code-pattern strings and `*.googleapis.com` API hosts (lessons.md item 12). The `docs/slug` placeholder in the inventory scope paragraph is not a URL to check.")
A("- Re-read due at P7 (verifier) and P9: release notes (PERSON_NAME promotion about 2026-11-02, MEDICAL_ID legacy window about 2026-10-11), limits page, infoType reference counts.")
A("- Cross-product headers (Model Armor MA5, MA6, MA10; Presidio PD1, PD2; Sentinel SN6) match the P2 drafts and CP1 rulings; re-compare when modelarmor_two_level.md and presidio_two_level.md exist.")
A("")
A("A 'Verifier fixes' section is appended below at P7 if the fresh verifier requires fixes.")
A("")
open(ROOT + "sdp_changes.md", "w", encoding="utf-8").write("\n".join(t))
print(len("\n".join(t)))
